import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { useLanguage } from '@/contexts/LanguageContext';
import { SectionHeader } from './SectionHeader';


export const LumpSumDCAFAQSection = () => {
  const { language } = useLanguage();
  const tr = language === 'tr';

  const faqs = [
    { question: tr ? 'Toplu yatırım ile DCA arasındaki fark nedir?' : "What's the difference between lump sum and DCA investing?", answer: tr ? 'Toplu yatırım, tüm paranızı bir anda Bitcoin’e koymak demektir; Dolar Maliyeti Ortalaması (DCA) ise alımlarınızı düzenli aralıklarla zamana yaymaktır. Toplu yatırım piyasada geçirilen süreyi maksimize eder ancak zamanlama riski taşır; DCA ise yatırım dönemi boyunca fiyat dalgalanmalarını ortalayarak bu riski azaltır.' : 'Lump sum investing means putting all your money into Bitcoin at once, while Dollar Cost Averaging (DCA) means spreading your purchases over time at regular intervals. Lump sum maximizes time in the market but carries timing risk, while DCA reduces timing risk by averaging out price fluctuations over your investment period.' },
    { question: tr ? 'Bitcoin için hangi strateji daha iyidir?' : "Which strategy is better for Bitcoin?", answer: tr ? 'Evrensel olarak “daha iyi” bir strateji yoktur; piyasa koşullarına ve kişisel durumunuza bağlıdır. Tarihsel olarak, toplu yatırım güçlü boğa piyasalarında genellikle kazanır çünkü yükselişten en yüksek maruziyeti sağlar. DCA ise daha düşük fiyatlara ortalama maliyetle girildiği için oynak veya düşüşteki piyasalarda daha iyi performans gösterir. Hesaplayıcımız, seçtiğiniz dönemde her birinin nasıl performans göstereceğini net olarak gösterir.' : 'There\'s no universally "better" strategy - it depends on market conditions and personal circumstances. Historically, lump sum often wins in strong bull markets because you get maximum exposure to gains. DCA tends to perform better in volatile or declining markets because you average into lower prices. Our calculator shows you exactly how each would have performed in your chosen time period.' },
    { question: tr ? 'Dolar Değeri Ortalaması (DVA) nedir?' : 'What is Dollar Value Averaging (DVA)?', answer: tr ? 'Dolar Değeri Ortalaması (DVA), portföyünüzün her dönemde sabit bir hedef miktar kadar büyümesi için her periyottaki yatırım tutarını ayarladığınız bir stratejidir. DCA’nın sabit tutarlı alımlarının aksine, DVA fiyatlar düştüğünde daha fazla, fiyatlar yükseldiğinde daha az yatırım yapar. Bu sistematik yaklaşım, sabit harcamadan ziyade tutarlı portföy büyümesini hedefler.' : 'Dollar Value Averaging (DVA) is a strategy where you adjust each periodic investment so your portfolio grows by a fixed target amount each period. Unlike DCA\'s fixed investment amounts, DVA invests more when prices drop (buying cheaper Bitcoin) and less when prices rise. This systematic approach targets consistent portfolio growth rather than consistent spending.' },
    { question: tr ? 'DVA, DCA’dan nasıl farklıdır?' : 'How does DVA differ from DCA?', answer: tr ? 'DCA’da her dönemde fiyat ne olursa olsun aynı miktarı yatırırsınız. DVA’da ise yatırım tutarı değişir — portföyünüz hedefin altındaysa (fiyatlar düşmüşse) daha fazla, hedefin üstündeyse (fiyatlar yükselmişse) daha az yatırım yaparsınız. DVA, daha düşük fiyatlarda doğal olarak daha fazla alım yaptığı için DCA’yı geçebilir; ancak yatırım tutarları her dönemde değiştiğinden daha esnek nakit akışı gerektirir.' : 'With DCA, you invest the same dollar amount each period regardless of price. With DVA, the investment amount varies — you invest more when your portfolio is below target (prices dropped) and less when it\'s above target (prices rose). DVA can potentially outperform DCA by naturally buying more at lower prices, but requires more flexible cash flow since investment amounts change each period.' },
    { question: tr ? 'Piyasa oynaklığı her stratejiyi nasıl etkiler?' : 'How does market volatility affect each strategy?', answer: tr ? 'Yüksek volatilite genellikle DCA ve DVA lehinedir çünkü fiyatlar düşükken daha fazla Bitcoin alırlar. DVA, fiyatlar düştüğünde yatırımı otomatik olarak artırdığı için özellikle oynak piyasalarda etkilidir. Toplu yatırım ise oynak piyasalarda daha fazla risk taşır — zirvede alım yapabilirsiniz ya da dipten alma avantajı yakalayabilirsiniz.' : 'High volatility generally favors DCA and DVA because they buy more Bitcoin when prices are low. DVA is especially effective in volatile markets since it automatically increases investment when prices drop. Lump sum investing in volatile markets carries more risk - you might buy at a peak or benefit from buying at a low.' },
    { question: tr ? 'Elimde toplu para yoksa ne olur?' : "What if I don't have a lump sum available?", answer: tr ? 'Eğer tek seferde büyük bir tutar yatırmıyorsanız, DCA genellikle en pratik seçenektir. Birçok yatırımcı, büyük bir tutar biriktirmeyi beklemek yerine gelirlerinden düzenli olarak yatırım yapabildikleri için DCA’yı tercih eder. Bu hesaplayıcı, mevcut tutarınızın farklı DCA sıklıklarıyla nasıl performans göstereceğini ve toplu yatırım için beklemenin ne kadar avantaj sağlayabileceğini görmenize yardımcı olur.' : "If you don't have a large amount to invest at once, DCA is often the practical choice. Many investors prefer DCA because it allows them to invest consistently from their income without waiting to accumulate a large sum. This calculator can help you see how your available amount would perform with different DCA frequencies versus saving up for a lump sum investment." },
    { question: tr ? 'Psikolojik faktörler hesaba katılıyor mu?' : 'Does this account for psychological factors?', answer: tr ? 'Hesaplayıcımız matematiksel performansa odaklansa da psikoloji yatırım başarısında büyük rol oynar. Toplu yatırım, büyük tek seferlik yatırım ve volatiliteye anında maruz kalma nedeniyle kaygı yaratabilir. DCA ise yatırımlar daha küçük ve yayılmış olduğu için daha rahat hissettirebilir; bu da piyasa dalgalanmalarının duygusal etkisini azaltır.' : 'While our calculator focuses on mathematical performance, psychology plays a huge role in investing success. Lump sum investing can create anxiety due to the large single investment and immediate exposure to volatility. DCA often feels more comfortable because investments are smaller and spread out, reducing the emotional impact of market fluctuations.' },
    { question: tr ? 'Tarihsel karşılaştırmalar ne kadar doğru?' : 'How accurate are historical comparisons?', answer: tr ? 'Hesaplamalarımız, geçmiş performansın doğru temsillerini sağlamak için gerçek tarihsel Bitcoin fiyat verilerini kullanır. Ancak geçmiş performans, gelecekteki sonuçları garanti etmez. Kripto para piyasaları oldukça oynak ve tahmin edilemezdir. Bu araç, bu stratejilerin tarihsel olarak nasıl çalıştığını anlamak içindir; geleceği tahmin etmek için değil.' : 'Our calculations use real historical Bitcoin price data to provide accurate representations of past performance. However, past performance does not guarantee future results. Cryptocurrency markets are highly volatile and unpredictable. This tool is for educational purposes to understand how these strategies have worked historically, not to predict future performance.' },
    { question: tr ? 'İşlem ücretleri ne olacak?' : 'What about transaction fees?', answer: tr ? 'Hesaplayıcımız, borsalar arasında büyük farklılık gösterebilen işlem ücretlerini hesaba katmadan ham strateji performansını gösterir. Pratikte DCA ve DVA, birden fazla işlem nedeniyle genellikle daha fazla ücret doğurur; toplu yatırımda ise tek bir işlem maliyeti vardır. Uygularken borsanızın ücret yapısını dikkate alın, çünkü bu genel getiriyi etkileyebilir.' : 'Our calculator shows raw strategy performance without factoring in transaction fees, which can vary significantly between exchanges. In practice, DCA and DVA typically incur more fees due to multiple transactions, while lump sum has a single transaction cost. When implementing either strategy, consider your exchange\'s fee structure as it can impact your overall returns.' },
    { question: tr ? 'Bunu diğer dönemler için kullanabilir miyim?' : 'Can I use this for other time periods?', answer: tr ? 'Evet! Hesaplayıcımız esnektir ve Bitcoin fiyat geçmişinin başladığı herhangi bir tarihsel dönem için stratejileri karşılaştırmanıza izin verir. Farklı piyasa döngülerini, ayı piyasalarını, boğa piyasalarını veya ilgilendiğiniz belirli dönemleri test edebilirsiniz. Bu, her stratejinin farklı piyasa koşullarında nasıl performans gösterdiğini anlamanıza yardımcı olur.' : 'Yes! Our calculator is flexible and allows you to compare strategies across any historical time period since Bitcoin\'s price history began. You can test different market cycles, bear markets, bull markets, or specific periods that interest you. This helps you understand how each strategy performs in different market conditions.' },
    { question: tr ? 'En iyi DCA sıklığı nedir?' : "What's the best DCA frequency?", answer: tr ? 'En uygun DCA sıklığı durumunuza ve piyasa koşullarına bağlıdır. Günlük DCA en fazla fiyat ortalamasını sağlar ancak ücretler daha yüksek olabilir. Haftalık veya iki haftada bir alımlar, ortalama maliyet ile daha düşük ücretler arasında denge kurabilir. Aylık DCA ise maaş ödemeleriyle uyumlu olduğu için popülerdir. Hesaplayıcımız, farklı sıklıkların tarihsel etkisini test etmenize izin verir.' : 'The optimal DCA frequency depends on your situation and market conditions. Daily DCA provides the most price averaging but may have higher fees. Weekly or bi-weekly can balance averaging with lower fees. Monthly DCA is popular because it aligns with salary payments. Our calculator lets you test different frequencies to see their historical impact.' },
    { question: tr ? 'Piyasa koşullarını dikkate almalı mıyım?' : 'Should I consider market conditions when choosing?', answer: tr ? 'Piyasa koşulları strateji etkinliğini etkileyebilir, ancak piyasayı tutarlı şekilde zamanlamak son derece zordur. Genel olarak, piyasanın yükseleceğine inanıyorsanız toplu yatırım iyi çalışır; devam eden volatilite bekliyorsanız DCA daha iyi olabilir. Ancak Bitcoin’in uzun vadeli yönü tahmin edilemez olduğundan, birçok yatırımcı piyasa koşullarından bağımsız olarak risk azaltımı nedeniyle DCA’yı seçer.' : 'Market conditions can influence strategy effectiveness, but timing the market consistently is extremely difficult. In general, lump sum works well when you believe the market will trend upward, while DCA can be better when you expect continued volatility. However, since Bitcoin\'s long-term direction is unpredictable, many investors choose DCA for its risk reduction benefits regardless of market conditions.' },
    { question: tr ? 'Bitcoin tarihinde toplu yatırım ne sıklıkla DCA’yı geçti?' : 'How often does lump sum beat DCA in Bitcoin\'s history?', answer: tr ? '2013’ten bu yana kaydırmalı 12 aylık giriş dönemlerinin tamamında, elde tutma süresi 4 yılı aştığında toplu yatırım 12 aylık DCA’yı zamanın yaklaşık %60’ında geride bırakmıştır. Önceki bir tüm zamanların zirvesinden sonraki 90 gün içinde yatırım yapmaya başladığınızda kazanç oranı DCA lehine (yaklaşık %65) döner. İstediğiniz herhangi bir tarih aralığını test etmek için yukarıdaki geriye dönük testi kullanın.' : 'Across all rolling 12-month entry periods since 2013, lump sum has outperformed 12-month DCA roughly 60% of the time when the holding period extends beyond 4 years. The win rate flips in DCA\'s favor (around 65%) when you start investing within 90 days of a previous all-time high. Use the backtest above to test any specific date range.' },
    { question: tr ? '50/50 hibrit strateji nedir?' : 'What is the 50/50 hybrid strategy?', answer: tr ? '50/50 hibrit, sermayenizi ikiye böler: yarısını hemen toplu yatırım olarak yapar ve diğer yarısını 6-12 ay boyunca DCA ile dağıtırsınız. Bu, toplu yatırımın beklenen getirisinin yaklaşık %80’ini korurken zamanlama riski varyansını yarıya indirir. Tüm sermayeye gitmekten rahatsız olan müşteriler için çoğu kurumsal tahsisçinin önerdiği yaklaşımdır.' : 'The 50/50 hybrid splits your capital: invest half as a lump sum immediately and DCA the other half over 6-12 months. This captures roughly 80% of lump sum\'s expected return while cutting timing-risk variance in half. It\'s the approach most institutional allocators recommend for clients uncomfortable going all-in.' },
    { question: tr ? 'DCA’nın fırsat maliyeti nedir?' : 'What is the opportunity cost of DCA?', answer: tr ? 'DCA yerine toplu yatırım yapmadığınızda, yatırım yapmadığınız nakit yaklaşık %4-5 getiren bir yüksek getirili tasarruf hesabında kalırken Bitcoin’in ortalama ~%60 yıllık getirisini kaçırırsınız. Boğa piyasalarında bu, binlerce dolar kaçırılmış kazanca yol açabilir. Ayı piyasalarında ise düşüşlerden korunursunuz. DCA esasen bir volatilite sigortasıdır.' : 'When you DCA instead of lump sum, your uninvested cash earns ~4-5% in a high-yield savings account while missing Bitcoin\'s average ~60% annual return. In bull markets, this can cost thousands in foregone gains. In bear markets, it saves you from drawdowns. DCA is essentially a volatility insurance policy.' },
    { question: tr ? 'Yeni toplu para geldiyse toplu yatırım yapmalı mıyım?' : 'Should I lump sum if I just received a windfall?', answer: tr ? 'İstatistiksel olarak evet — matematik hemen yatırmayı destekler. Ancak davranışsal olarak, büyük toplu paralar yatırımcıların en çok ikinci kez düşündüğü anlardır. Yaygın bir uzlaşma: ilk hafta içinde %25-50’yi yatırın, ardından kalanı 3-6 ay boyunca DCA yapın. Bu, psikolojinizi ani bir düşüşe karşı korurken hızlı maruziyet sağlar.' : 'Statistically yes — the math favors immediate deployment. But behaviorally, large windfalls are also when investors are most prone to second-guessing. A common compromise: deploy 25-50% within the first week, then DCA the rest over 3-6 months.' },
    { question: tr ? 'DCA, halving yıllarında daha mı iyi çalışır?' : 'Does DCA work better during halving years?', answer: tr ? 'Tarihsel olarak, bir halving öncesindeki 12 ayda başlayan DCA, toplu yatırımı zamanın yaklaşık %70’inde geçmiştir; çünkü halving döngüleri genellikle konsolidasyonla başlayıp 6-18 ay sonra ivmelenir. Bu da DCA’nın halving sonrası ralli başlamadan önce daha düşük fiyatlardan birikim yapmasını sağlar.' : 'Historically, DCA started in the 12 months before a halving has outperformed lump sum about 70% of the time, because halving cycles tend to start with consolidation followed by acceleration in the 6-18 months after.' },
    { question: tr ? 'DCA ve toplu yatırım için vergiler ne olacak?' : 'What about taxes on DCA vs lump sum?', answer: tr ? 'DCA, her biri kendi elde tutma süresi ve alış fiyatına sahip birden fazla maliyet tabanı lotu oluşturur. Bu, vergi raporlamasını karmaşıklaştırır ancak vergi kaybı hasadı avantajı sağlar: kazanan lotları tutarken kaybeden lotları zararına satabilirsiniz. Toplu yatırım tek bir maliyet tabanına ve tek bir elde tutma süresine sahiptir — daha basit ama daha az esnektir.' : 'DCA creates multiple cost-basis lots, each with its own holding period and acquisition price. This complicates tax reporting but offers a tax-loss-harvesting advantage: you can sell specific lots at losses while keeping winning lots. Lump sum has a single cost basis and one holding period — simpler but less flexible.' }
  ];

  return (
    <div className="max-w-4xl mx-auto">
      <SectionHeader
        eyebrow="FAQ"
        title={tr ? 'Sık Sorulan Sorular' : 'Frequently Asked Questions'}
        lead={tr
          ? 'Toplu yatırım, DCA ve DVA stratejileri hakkında yaygın soruların yanıtları.'
          : 'Answers to common questions about lump sum, DCA, and DVA strategies.'}
      />
      <Accordion type="single" collapsible className="space-y-4">
        {faqs.map((faq, index) => (
          <AccordionItem key={index} value={`item-${index}`} className="bg-card border border-border/50 rounded-xl px-6">
            <AccordionTrigger className="text-left font-medium text-foreground hover:text-primary py-5 text-base">{faq.question}</AccordionTrigger>
            <AccordionContent className="text-muted-foreground pb-5 text-sm leading-relaxed">{faq.answer}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
};