import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { useLanguage } from "@/contexts/LanguageContext";
import { renderInlineMarkdown } from "@/components/learn/ArticleContent";
import { SectionHeader } from "./SectionHeader";

export const RetirementFAQSection = () => {
  const { language } = useLanguage();
  const tr = language==='tr';
  const faqData = tr ? [
    { question: "'Tahminci' ile 'Hedef Planlayıcı' arasındaki fark nedir?", answer: "Şöyle düşünün: Mevcut rotanızın sizi nereye götürdüğünü görmek için Tahminci'yi kullanın. Tam olarak istediğiniz yere ulaşmak için yeni bir rota oluşturmak üzere Hedef Planlayıcı'yı kullanın. Tahminci mevcut planınızı analiz eder, Hedef Planlayıcı ise size yeni bir plan kurar." },
    { question: "'Gerekli Aylık Katkı' çok yüksekse ne yapmalıyım?", answer: "Hedefinizin yüksek katkı gerektirdiğini görmek değerli bir içgörüdür. Tutar şu an gerçekçi değilse, denge bulmak için planlayıcıyı kullanın. Diğer değişkenleri ayarlayın. Örneğin emeklilik yaşını birkaç yıl artırmak veya biraz daha yüksek bir 'Beklenen Büyüme Oranı' modellemek gereken aylık yatırımı ciddi biçimde azaltabilir." },
    { question: "Hedef Planlayıcı 'Gerekli Toplam BTC'yi nasıl hesaplıyor?", answer: "Planlayıcı standart bir finans prensibi olan **4% para çekme kuralı**nı kullanır. Önce 'İstenen Yıllık Bütçe'nizin sürdürülebilir bir yıllık %4 çekime eşit olacağı toplam emeklilik fonunu hesaplar. Ardından beklenen büyüme ve enflasyon oranlarınızı hesaba katarak bu fonu oluşturmak için emeklilik tarihine kadar biriktirmeniz gereken nihai BTC miktarını belirler." },
    { question: "Emekli olmak için ne kadar Bitcoin gerekir?", answer: "Bu en yaygın sorudur ve cevap size özeldir. İstenen yıllık geliriniz, yaşam tarzınız ve para çekme stratejinize bağlıdır. Bitcoin fiyatı 500.000 $ olduğunda, 1 BTC 4% kuralıyla yılda 20.000 $ üretir — dünyanın birçok yerinde mütevazı bir emeklilik için yeterli olabilir. Aynı fiyatta 5 BTC yıllık 100.000 $'a çıkar. Farklı fiyat hedefleriyle kendi senaryonuzu modellemek için yukarıdaki hesap makinesini kullanın." },
    { question: "1 Bitcoin ile emekli olabilir miyim?", answer: "Tamamen Bitcoin'in gelecekteki fiyatına ve yıllık giderlerinize bağlıdır. BTC başına 100.000 $'da 1 Bitcoin, 4% kuralıyla yılda yalnızca 4.000 $ üretir — çoğu insan için yeterli değildir. BTC başına 500.000 $'da yıllık 20.000 $ üretir, bu da düşük yaşam maliyetli bölgelerde işe yarayabilir. BTC başına 1.000.000 $'da 1 Bitcoin yıllık 40.000 $ sağlar. FIRE Modu'nu kullanarak 1 BTC'nin giderlerinizi tam olarak ne zaman karşılayabileceğini görün." },
    { question: "Bitcoin emeklilik planlamasında hangi büyüme oranını kullanmalıyım?", answer: "Gerçekçi bir aralık görmek için en az üç senaryo çalıştırmanızı öneririz. Muhafazakâr tahmin olarak %8-12'yi (tarihsel borsa getirilerine benzer), orta Bitcoin odaklı oran olarak %15-20'yi ve Bitcoin'in tarihsel üstün performansını yansıtan iyimser senaryo olarak %25+'ı kullanın. Tek bir sayı 'doğru' değildir — bu hesap makinesinin gücü, farklı varsayımlar altındaki sonuçları karşılaştırabilmenizdir." },
    { question: "Bitcoin DCA emeklilik planlamasına nasıl yardımcı olur?", answer: "Dolar maliyet ortalaması (DMA), fiyat ne olursa olsun her ay sabit bir tutarı Bitcoin'e yatırmak demektir. Uzun vadede DMA, volatiliteyi yumuşatır ve bileşik büyüme sayesinde varlıklarınızı önemli ölçüde artırabilir. Örneğin ayda 500 $'ı 20 yıl boyunca yatırmak, güncel fiyatlarda bile önemli miktarda Bitcoin biriktirir. Tahminci modu bunu doğrudan modellemenize olanak tanır — emeklilik portföyünüz üzerindeki tahmini etkiyi görmek için aylık katkınızı girin." },
    { question: "Planım gerçek olamayacak kadar iyi görünüyor. Bu simülasyon fazla iyimser mi?", answer: "Şüpheci olmak yerindedir. Hesap makinemiz bir tahmin aracıdır, garanti değildir. Sonuç, girdiğiniz 'Beklenen Büyüme Oranı'na büyük ölçüde bağlıdır. Birden fazla simülasyon çalıştırmanızı kuvvetle öneririz: biri muhafazakâr oranla (ör. %8-12), biri orta oranla ve biri iyimser bir 'ay'a' senaryosuyla. Bu, olasılıkların daha gerçekçi bir aralığını sağlar ve hem potansiyeli hem de riskleri anlamanıza yardımcı olur." },
    { question: "Emeklilikte Bitcoin'den yaşamak için farklı yollar nelerdir? Satmak zorunda mıyım?", answer: "Çoğu emeklilik planı, yaşam tarzınızı finanse etmek için zaman içinde Bitcoin'inizi satacağınızı varsayar (hesap makinemiz bunu mükemmel biçimde modeller). Ancak daha gelişmiş kullanıcılar, alttaki varlığı satmadan gelir yaratmak için Bitcoin'e karşı borçlanma gibi başka seçenekleri de inceler. Aracımız doğrudan satış modeline odaklansa da, her strateji için ihtiyaç duyacağınız başlangıç sermayesini belirlemede güçlüdür." },
    { question: "Bu geleneksel bir emeklilik planıyla nasıl karşılaştırılır?", answer: "Geleneksel emeklilik planı genellikle hisse senedi ve tahviller gibi Bitcoin'e kıyasla daha düşük volatiliteye sahip varlıklara dayanır. Bitcoin ise daha yeni bir varlık sınıfıdır; daha yüksek büyüme potansiyeli ama daha yüksek risk de taşır. Birçok kullanıcı Bitcoin'i geleneksel birikimlerinin yerine değil, finansal özgürlüğe giden yolu hızlandırabilecek güçlü bir ek olarak görür. Aracımız bu hızlanmanın nasıl görünebileceğini görselleştirmenize yardımcı olur." },
    { question: "Bu hesap makinesi enflasyonu nasıl hesaba katıyor?", answer: "Enflasyon kritik bir faktördür ve doğrudan modelimize dahildir. 'Enflasyon Oranı' girdiğinizde hesap makinesi paranızın satın alma gücünü zaman içinde otomatik olarak ayarlar. Bu, emeklilikteki 'Yıllık Bütçe'nizin gerçek dünya maliyetlerini yansıtmasını sağlar ve rahat yaşamak için ne kadar gerekeceğini eksik tahmin etme hatasını önler." },
    { question: "Bu Bitcoin emeklilik hesaplayıcısı tamamen ücretsiz mi?", answer: "Evet, bu aracı kullanmak %100 ücretsizdir. Bitcoin topluluğu için erişilebilir finansal planlama araçları sağlamaya inanıyoruz. Emeklilik senaryonuzu tahmin etmek için abonelik veya gizli ücret yoktur." },
    { question: "Bu hesap makinesini uygulama ya da Excel olarak indirebilir miyim?", answer: "Şu anda bu, mobil telefonlar dahil herhangi bir cihazın tarayıcısında sorunsuz çalışan web tabanlı bir araçtır. İndirilecek ayrı bir mobil uygulama ya da Excel sürümü yoktur; böylece her zaman canlı fiyat verileriyle en güncel sürümü kullanırsınız." },
    { question: "Bu hangi tahmin modelini kullanıyor? Power Law tabanlı mı?", answer: "Bu hesap makinesi esnek bir Bileşik Yıllık Büyüme Oranı (BYBBO/CAGR) modeli kullanır. Tek bir Power Law modeli yerine, aracımız size kendi 'Beklenen Büyüme Oranı'nızı belirleme gücü verir. Bu sayede muhafazakâr planlardan daha iyimser tahminlere kadar geniş bir senaryo aralığını simüle edebilir, emeklilik stratejinizdeki varsayımları tamamen kontrol edebilirsiniz." },
    { question: "Nasıl bir 'ay'a' veya hiper-büyüme senaryosu modelleyebilirim?", answer: "Bu araçla hiper-büyüme veya 'moon' senaryolarını kolayca simüle edebilirsiniz. 'Beklenen Büyüme Oranı' alanına çok yüksek bir yıllık yüzde girmeniz yeterlidir. Hesap makinesi, portföyünüzü bu agresif tahmine göre projelendirecektir. Unutmayın, olasılıkları görmek faydalı olsa da bu projeksiyonlar eğitim amaçlıdır ve daha yüksek potansiyel ödüller daha yüksek riskle gelir." },
    { question: "Planım için gerçekçi bir 'Beklenen Büyüme Oranı' nedir?", answer: "Büyüme oranı seçimi risk toleransınıza bağlıdır. Daha muhafazakâr bir tahmin için tarihsel borsa getirilerine benzer bir oran (%8-12 gibi) kullanabilirsiniz. Daha iyimser bir Bitcoin senaryosu için bazı kullanıcılar Bitcoin'in tarihsel performansını yansıtan %20-50 arası oranlar modellemektedir; ancak geçmiş sonuçlar gelecekteki getirileri garanti etmez. Olası sonuçların tam aralığını görmek için birden fazla oranla hesaplama yapmanızı öneririz." },
    { question: "Temkinli ve Optimize emeklilik modları arasındaki fark nedir?", answer: "Temkinli mod, emeklilikte tüm Bitcoin'inizi satacağınızı ve elde edilen fiat üzerinden geleneksel %4 çekim kuralını izleyeceğinizi varsayar. Optimize mod ise emeklilik sırasında Bitcoin'e yatırımda kalmanızı sağlar; böylece varlıklarınız büyümeye devam ederken her yıl mevcut portföy değerinizin %4'ünü çekersiniz. Bu strateji Bitcoin maruziyetini korur ama daha yüksek volatilite riski taşır." },
    { question: "Bitcoin emekliliğimden önce sıfıra giderse ya da geçersiz kalırsa ne olur?", answer: "Bu, her Bitcoin emeklilik stratejisinde dikkate alınması gereken önemli bir risktir. Hesap makinesi teknolojik eskime, düzenleyici yasaklar veya katastrofik güvenlik sorunları gibi varoluşsal riskleri hesaba katamaz. Bu nedenle finans danışmanları, tüm emeklilik birikimini ne kadar iyi görünse de tek bir varlığa koymamanızı önerir. Bitcoin'i çeşitlendirilmiş bir emeklilik stratejisinin parçası olarak düşünün." },
    { question: "Bitcoin emeklilik çekimlerimi vergiler nasıl etkiler?", answer: "ABD'de Bitcoin'i satmak, bir yıldan fazla tutulmuşsa uzun vadeli sermaye kazancı vergisi doğurur. Oranlar vergilendirilebilir gelirinize göre %0 ile %20 arasında değişir; yüksek gelir grupları için ek %3,8 NIIT (Net Investment Income Tax) uygulanabilir. Çekimlerinizi belirli gelir eşiklerinin altında tutacak şekilde yapılandırmak yılda binlerce dolar tasarruf sağlayabilir. Ayrıntılı projeksiyonlar için Bitcoin Vergi Hesaplayıcımızı kullanmayı düşünün." },
    { question: "Bitcoin emekliliğinde sıralı getiri riski nedir?", answer: "Sıralı getiri riski, emekliliğin ilk birkaç yılında yaşanan büyük piyasa çöküşünün, ortalama getirileriniz pozitif olsa bile portföyünüzü kalıcı olarak zedelemesi anlamına gelir. Bitcoin ilk yılınızda %60 düşer ve masrafları karşılamak için satarsanız, zararı kilitlemiş olursunuz. Bunu azaltmak için 2 yıllık nakit veya stablecoin tamponu tutmak ve döngü farkındalıklı çekim oranları kullanmak yararlıdır." },
    { question: "Bitcoin IRA mı kullanmalıyım yoksa BTC'yi doğrudan mı tutmalıyım?", answer: "Kendi kendine yönetilen bir Bitcoin IRA, vergi avantajlı büyüme (Geleneksel) veya vergisiz çekim (Roth) sunar; ancak saklama ücretleri, düzenleyici karmaşıklık ve kendi kendine saklama kısıtları içerir. BTC'yi doğrudan tutmak tam egemenlik ve daha düşük maliyet sağlar; ancak her satış vergilendirilebilir bir olaydır. Birçok emekli, temel tahsis için IRA ve esneklik için doğrudan saklama arasında bölüşüm yapar." },
    { question: "FIRE Modu Tahminci'den nasıl farklıdır?", answer: "Tahminci, mevcut tasarruf planınızın zaman içinde sizi nereye götüreceğini projelendirir. FIRE Modu ise geriye doğru çalışır — yıllık giderlerinizi ve çekim oranınızı alır, ardından Bitcoin portföyünüzün bu giderleri dört büyüme senaryosunda (Ayı, Base, Boğa ve Hiper) süresiz olarak ne zaman karşılayabileceğini hesaplar. 'Ne zaman bırakabilirim?' sorusunu, 'Neye sahip olacağım?' sorusu yerine yanıtlar." },
    { question: "Ayı piyasasında Bitcoin emeklilik planıma ne olur?", answer: "Ayı piyasaları Bitcoin emeklileri için en büyük testtir. %4 sabit çekimle %70 düşüşte ilerlerseniz, planlanandan çok daha fazla BTC satarsınız. Döngü farkındalıklı yaklaşım, ayı dönemlerinde %2-3, boğa dönemlerinde %5-6 çekim yapar. Alternatif olarak 1-2 yıllık gideri stablecoin'de tutmak, düşüşlerde hiç BTC satmamanızı sağlar." },
    { question: "Bitcoin yığınımın emekliliğe yetip yetmeyeceğini nasıl anlarım?", answer: "Yıllık giderlerinizi 25 ile çarpın (%4 çekim kuralı), sonucu tuttuğunuz BTC miktarına bölün — çıkan rakam, yığınınızın emekliliği karşıladığı BTC fiyatıdır. Örnek: yılda 500.000 ₺ × 25 = 12,5 milyon ₺; 2 BTC tutuyorsanız BTC 6,25 milyon ₺'ye ulaştığında emekli olursunuz. FIRE Modu'nu kendi sayılarınızla çalıştırın." },
    { question: "Bitcoin'i geleneksel emeklilik hesaplarıyla birleştirebilir miyim?", answer: "Kesinlikle — hatta çoğu finans danışmanı bunu önerir. Yaygın strateji, asimetrik yükseliş için emeklilik portföyünün %5-20'sini Bitcoin'de tutarken kalanını geleneksel endeks fonları, tahviller ve gayrimenkulde bırakmaktır. Bu çeşitlendirme, Bitcoin'e özgü risklere karşı koruma sağlarken büyüme potansiyelini de yakalar." },
  ] : [
    { question: "What's the difference between the 'Forecaster' and the 'Goal Planner'?", answer: "Think of it this way: Use the Forecaster to see where your current path is leading. Use the Goal Planner to create a new path to get you exactly where you want to go. The Forecaster analyzes your current plan, while the Goal Planner builds you a new one." },
    { question: "What should I do if the 'Required Monthly Contribution' is too high?", answer: "Discovering that your goal requires a high contribution is a valuable insight! If the amount is unrealistic for you right now, use the planner to find a balance. Try adjusting other variables to see the impact. For example, increasing your retirement age by a few years or modeling a slightly higher 'Expected Growth Rate' can often significantly lower the required monthly investment." },
    { question: "How does the Goal Planner calculate the 'Total BTC Needed'?", answer: "The planner uses a standard financial principle: the **4% withdrawal rule**. It first calculates the total retirement fund needed so that your 'Desired Annual Budget' would equal a sustainable 4% annual withdrawal. It then factors in your expected growth and inflation rates to determine the final amount of BTC you would need to accumulate by your retirement date to create that fund." },
    { question: "How much Bitcoin do I need to retire?", answer: "This is the most common question, and the answer is unique to you. It depends on your desired annual income, lifestyle, and withdrawal strategy. At a Bitcoin price of $500,000, holding just 1 BTC would generate $20,000 per year using the 4% rule — enough for a modest retirement in many parts of the world. With 5 BTC at the same price, that jumps to $100,000 per year. Use the calculator above to model your specific scenario with different price targets." },
    { question: "Can I retire with 1 Bitcoin?", answer: "It depends entirely on the future price of Bitcoin and your annual expenses. At $100,000 per BTC, 1 Bitcoin generates just $4,000 per year using the 4% rule — not enough for most people. At $500,000 per BTC, it generates $20,000 per year, which could work in low-cost-of-living areas. At $1,000,000 per BTC, 1 Bitcoin supports $40,000 per year. Try the FIRE Mode above to see exactly when 1 BTC could cover your expenses." },
    { question: "What Bitcoin growth rate should I use for retirement planning?", answer: "We recommend running at least three scenarios to get a realistic range. Use **8–12%** as a conservative estimate (similar to historical stock market returns), **15–20%** as a moderate Bitcoin-specific rate, and **25%+** as an optimistic scenario reflecting Bitcoin's historical outperformance. No single number is \"correct\" — the power of this calculator is comparing outcomes across different assumptions." },
    { question: "How does Bitcoin DCA help with retirement planning?", answer: "Dollar-cost averaging (DCA) means investing a fixed amount in Bitcoin every month regardless of price. Over long time horizons, DCA smooths out volatility and can dramatically grow your holdings through compounding. For example, $500 per month over 20 years accumulates significant Bitcoin even at today's prices. Our Forecaster mode models this directly — enter your monthly contribution to see the projected impact on your retirement portfolio." },
    { question: "My plan looks too good to be true. Is this simulation overly optimistic?", answer: "It's wise to be skeptical. Our calculator is a forecasting tool, not a guarantee. The outcome is highly dependent on the \"Expected Growth Rate\" you input. We strongly recommend you run multiple simulations: one with a conservative rate (e.g., 8-12%), one with a moderate rate, and one with an optimistic \"moon\" scenario. This provides a more realistic range of possibilities and helps you understand both the potential and the risks." },
    { question: "What are the different ways to live off Bitcoin in retirement? Do I have to sell?", answer: "Most retirement plans assume you will sell your Bitcoin over time to fund your lifestyle (a strategy our calculator models perfectly). However, more advanced users explore other options, such as borrowing against their Bitcoin holdings to generate income without selling the underlying asset. While our calculator focuses on the direct sale model, it's a powerful tool for determining the initial capital you'd need for any strategy." },
    { question: "How does this compare to a traditional retirement plan?", answer: "A traditional retirement plan typically relies on assets like stocks and bonds, which are generally less volatile than Bitcoin. Bitcoin is a newer asset class with the potential for higher growth but also higher risk. Many users see Bitcoin not as a replacement for their traditional savings, but as a powerful addition to potentially accelerate their journey to financial independence. Our tool helps you visualize what that acceleration could look like." },
    { question: "How does this calculator account for inflation?", answer: "Inflation is a critical factor, and it's built directly into our model. When you input an \"Inflation Rate,\" the calculator automatically adjusts the purchasing power of your money over time. This ensures your \"Annual Budget\" in retirement reflects real-world costs, preventing the common mistake of underestimating how much you'll truly need to live comfortably." },
    { question: "Is this Bitcoin retirement calculator completely free?", answer: "Yes, this tool is 100% free to use. We believe in providing accessible financial planning tools to the Bitcoin community. There are no subscriptions or hidden charges required to forecast your retirement scenario." },
    { question: "Can I download this calculator as an app or Excel spreadsheet?", answer: "Currently, this is a web-based tool designed to work perfectly on any device's browser, including mobile phones. There is no dedicated mobile app or Excel version to download, which ensures you are always using the most up-to-date version with live price data." },
    { question: "What forecasting model does this use? Is it based on the Power Law?", answer: "This calculator uses a flexible Compound Annual Growth Rate (CAGR) model. Instead of relying on a single predictive model like the Power Law, our tool empowers you to set your own \"Expected Growth Rate.\" This allows you to simulate a wide range of scenarios, from conservative plans to more optimistic forecasts, giving you full control over the assumptions in your retirement strategy." },
    { question: "How can I model a \"wen MOON\" or hyper-growth scenario?", answer: "You can easily simulate hyper-growth or \"moon\" scenarios with this tool. In the \"Expected Growth Rate\" input field, simply enter a very high annual percentage. The calculator will then project your portfolio's value based on that aggressive forecast. Remember, while it's useful for seeing possibilities, these projections are for educational purposes, and higher potential rewards come with higher risk." },
    { question: "What is a realistic \"Expected Growth Rate\" to use for my plan?", answer: "Choosing a growth rate depends on your risk tolerance. For a more conservative estimate, you could use a rate similar to historical stock market returns (e.g., 8-12%). For a more optimistic Bitcoin-centric scenario, some users model rates between 20-50%, reflecting Bitcoin's historical performance, though past results don't guarantee future returns. We recommend running calculations with multiple rates to see a full range of potential outcomes." },
    { question: "What's the difference between Conservative and Optimized retirement modes?", answer: "Conservative mode assumes you sell all your Bitcoin at retirement and follow the traditional 4% withdrawal rule on the resulting fiat currency. Optimized mode keeps you invested in Bitcoin during retirement, allowing your remaining holdings to potentially continue growing while you withdraw 4% of your current portfolio value each year. This strategy maintains Bitcoin exposure but comes with higher volatility risk." },
    { question: "What if Bitcoin goes to zero or becomes obsolete before I retire?", answer: "This is an important risk to consider in any Bitcoin retirement strategy. The calculator cannot account for existential risks to Bitcoin such as technological obsolescence, regulatory bans, or catastrophic security failures. This is why financial advisors typically recommend not putting all retirement savings into any single asset, even one you're very optimistic about. Consider Bitcoin as part of a diversified retirement strategy." },
    { question: "How do taxes affect my Bitcoin retirement withdrawals?", answer: "In the United States, selling Bitcoin triggers long-term capital gains taxes if held for more than one year. Rates range from 0% to 20% depending on your taxable income, with a potential additional 3.8% NIIT (Net Investment Income Tax) for high earners. Structuring withdrawals to stay under certain income thresholds can save thousands annually. Consider using our Bitcoin Tax Calculator for detailed projections." },
    { question: "What is sequence-of-returns risk in Bitcoin retirement?", answer: "Sequence-of-returns risk means that a major market crash in the first few years of retirement can permanently damage your portfolio — even if average returns over your full retirement are positive. If Bitcoin drops 60% in your first year and you sell to cover expenses, you lock in losses. Mitigation strategies include maintaining a 2-year cash or stablecoin buffer and using cycle-aware withdrawal rates." },
    { question: "Should I use a Bitcoin IRA or hold BTC directly?", answer: "A self-directed Bitcoin IRA offers tax-advantaged growth (Traditional) or tax-free withdrawals (Roth), but comes with custodial fees, regulatory complexity, and restrictions on self-custody. Holding BTC directly gives you full sovereignty and lower costs, but every sale is a taxable event. Many retirees split their holdings — using an IRA for a base allocation and direct custody for flexibility." },
    { question: "How does the FIRE Mode differ from the Forecaster?", answer: "The Forecaster projects where your current savings plan leads over time. FIRE Mode works backward — it takes your annual expenses and withdrawal rate, then calculates the exact date when your Bitcoin portfolio could sustain those expenses indefinitely across four growth scenarios (Bear, Base, Bull, and Hyper). It answers 'When can I quit?' rather than 'What will I have?'" },
    { question: "What happens to my Bitcoin retirement plan during a bear market?", answer: "Bear markets are the biggest test for Bitcoin retirees. If you follow a fixed 4% withdrawal during a 70% drawdown, you sell far more BTC than planned. The cycle-aware approach withdraws 2-3% during bear markets and 5-6% during bull markets. Alternatively, maintaining 1-2 years of expenses in stablecoins lets you avoid selling BTC entirely during downturns." },
    { question: "Can I combine Bitcoin with traditional retirement accounts?", answer: "Absolutely — and most financial advisors recommend it. A common strategy is to hold 5–20% of your retirement portfolio in Bitcoin for asymmetric upside, while keeping the remainder in traditional index funds, bonds, and real estate. This diversification protects against Bitcoin-specific risks while still capturing its growth potential." },
  ];
  return <section className="py-16 md:py-20 bg-muted/30"><div className="container mx-auto px-6 max-w-4xl"><SectionHeader eyebrow={tr?'SSS':'FAQ'} title={tr?'Sıkça Sorulan Sorular':'Frequently Asked Questions'} lead={tr?'Bitcoin emeklilik planlaması ve bu hesap makinesi hakkında yaygın sorular.':'Common questions about Bitcoin retirement planning and how this calculator works.'} /><Accordion type="single" collapsible className="space-y-4">{faqData.map((faq, index) => (<AccordionItem key={index} value={`item-${index}`} className="bg-card border border-border/50 rounded-xl px-6"><AccordionTrigger className="text-left font-medium text-foreground hover:text-primary py-5 text-base">{faq.question}</AccordionTrigger><AccordionContent className="text-muted-foreground pb-5 text-sm leading-relaxed">{renderInlineMarkdown(faq.answer)}</AccordionContent></AccordionItem>))}</Accordion></div></section>;
};