import { useState } from "react";
import { ShareExportPanel } from "@/components/share-export";
import { useToast } from "@/hooks/use-toast";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { applyLocalizedPdfFont } from '@/utils/pdfFont';
import type { FeeEstimate, AllFeeEstimates, AddressType, Priority } from "@/services/transactionFeeCalculator";
import { useLanguage } from "@/contexts/LanguageContext";
import { buildExportFilename } from "@/utils/exportFilename";

interface FeeExportReportProps {
  selectedEstimate: FeeEstimate | null;
  allEstimates: AllFeeEstimates | null;
  addressType: AddressType;
  priority: Priority;
  inputCount: number;
  outputCount: number;
  btcPrice: number;
}

export const FeeExportReport = ({
  selectedEstimate,
  allEstimates,
  addressType,
  priority,
  inputCount,
  outputCount,
  btcPrice
}: FeeExportReportProps) => {
  const { language } = useLanguage();
  const tr = language === 'tr';
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const getAddressTypeLabel = (type: AddressType): string => {
    const labels: Record<AddressType, string> = {
      'legacy': 'Legacy (P2PKH)',
      'segwit': 'SegWit (P2SH-P2WPKH)',
      'native-segwit': 'Native SegWit (P2WPKH)',
      'taproot': 'Taproot (P2TR)'
    };
    return labels[type];
  };

  const getPriorityLabel = (p: Priority): string => {
    if (tr) {
      const labels: Record<Priority, string> = {
        'fastest': 'En Hızlı (~10 dk)',
        'halfHour': '30 Dakika',
        'hour': '1 Saat',
        'economy': 'Ekonomik (4+ saat)'
      };
      return labels[p];
    }
    const labels: Record<Priority, string> = {
      'fastest': 'Fastest (~10 min)',
      'halfHour': '30 Minutes',
      'hour': '1 Hour',
      'economy': 'Economy (4+ hours)'
    };
    return labels[p];
  };

  const generateReportElement = (): HTMLDivElement => {
    const report = document.createElement('div');
    report.style.cssText = `
      width: 800px;
      padding: 40px;
      background: #f5f3ee;
      color: #1a1a1a;
      font-family: system-ui, -apple-system, sans-serif;
    `;

    const date = new Date().toLocaleDateString(tr ? 'tr-TR' : 'en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    report.innerHTML = `
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 1px solid #e5e1d8;">
        <div>
          <h1 style="margin: 0; font-size: 28px; background: linear-gradient(135deg, #f7931a, #ffb347); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
            ${tr ? 'Bitcoin İşlem Ücreti Raporu' : 'Bitcoin Transaction Fee Report'}
          </h1>
          <p style="margin: 8px 0 0 0; color: rgba(26,26,26,0.6); font-size: 14px;">
            Generated by bitcoincalculator.tools
          </p>
        </div>
        <div style="text-align: right;">
          <p style="margin: 0; font-size: 12px; color: rgba(26,26,26,0.6);">${date}</p>
        </div>
      </div>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px;">
        <div style="background: #ffffff; padding: 20px; border-radius: 12px; border: 1px solid #e5e1d8;">
          <h3 style="margin: 0 0 15px 0; font-size: 14px; color: rgba(26,26,26,0.6); text-transform: uppercase;">${tr ? 'İşlem Parametreleri' : 'Transaction Parameters'}</h3>
          <p style="margin: 8px 0; font-size: 14px;"><strong>${tr ? 'Adres Türü:' : 'Address Type:'}</strong> ${getAddressTypeLabel(addressType)}</p>
          <p style="margin: 8px 0; font-size: 14px;"><strong>${tr ? 'Girdi:' : 'Inputs:'}</strong> ${inputCount}</p>
          <p style="margin: 8px 0; font-size: 14px;"><strong>${tr ? 'Çıktı:' : 'Outputs:'}</strong> ${outputCount}</p>
          <p style="margin: 8px 0; font-size: 14px;"><strong>${tr ? 'TX Boyutu:' : 'TX Size:'}</strong> ${selectedEstimate?.estimatedSize || 0} vBytes</p>
        </div>
        <div style="background: rgba(247, 147, 26, 0.1); padding: 20px; border-radius: 12px; border: 1px solid rgba(247, 147, 26, 0.3);">
          <h3 style="margin: 0 0 15px 0; font-size: 14px; color: #f7931a; text-transform: uppercase;">${tr ? 'Seçilen Ücret' : 'Selected Fee'}</h3>
          <p style="margin: 8px 0; font-size: 24px; font-weight: bold; color: #f7931a;">${selectedEstimate?.satsPerVbyte || 0} sat/vB</p>
          <p style="margin: 8px 0; font-size: 14px;"><strong>${tr ? 'Toplam:' : 'Total:'}</strong> ${selectedEstimate?.totalFeeSats.toLocaleString() || 0} sats</p>
          <p style="margin: 8px 0; font-size: 14px;"><strong>USD:</strong> $${selectedEstimate?.totalFeeUsd.toFixed(4) || '0.00'}</p>
          <p style="margin: 8px 0; font-size: 14px;"><strong>${tr ? 'Öncelik:' : 'Priority:'}</strong> ${getPriorityLabel(priority)}</p>
        </div>
      </div>

      <div style="background: #ffffff; padding: 20px; border-radius: 12px; border: 1px solid #e5e1d8; margin-bottom: 30px;">
        <h3 style="margin: 0 0 15px 0; font-size: 14px; color: rgba(26,26,26,0.6); text-transform: uppercase;">${tr ? 'Tüm Ücret Seçenekleri' : 'All Fee Options'}</h3>
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          <thead>
            <tr style="border-bottom: 1px solid #e5e1d8;">
              <th style="padding: 10px; text-align: left; color: rgba(26,26,26,0.6);">${tr ? 'Öncelik' : 'Priority'}</th>
              <th style="padding: 10px; text-align: right; color: rgba(26,26,26,0.6);">${tr ? 'Oran' : 'Rate'}</th>
              <th style="padding: 10px; text-align: right; color: rgba(26,26,26,0.6);">${tr ? 'Toplam (sats)' : 'Total (sats)'}</th>
              <th style="padding: 10px; text-align: right; color: rgba(26,26,26,0.6);">USD</th>
              <th style="padding: 10px; text-align: right; color: rgba(26,26,26,0.6);">${tr ? 'Süre' : 'Time'}</th>
            </tr>
          </thead>
          <tbody>
            ${allEstimates ? Object.entries(allEstimates).map(([key, est]) => `
              <tr style="border-bottom: 1px solid #ece7dd; ${key === priority ? 'background: rgba(247, 147, 26, 0.1);' : ''}">
                <td style="padding: 10px; ${key === priority ? 'color: #f7931a;' : ''}">${getPriorityLabel(key as Priority)}</td>
                <td style="padding: 10px; text-align: right; font-family: monospace;">${est.satsPerVbyte} sat/vB</td>
                <td style="padding: 10px; text-align: right; font-family: monospace;">${est.totalFeeSats.toLocaleString()}</td>
                <td style="padding: 10px; text-align: right;">$${est.totalFeeUsd.toFixed(4)}</td>
                <td style="padding: 10px; text-align: right; color: rgba(26,26,26,0.6);">${est.confirmationTime}</td>
              </tr>
            `).join('') : ''}
          </tbody>
        </table>
      </div>

      <div style="text-align: center; padding-top: 20px; border-top: 1px solid #e5e1d8;">
        <p style="margin: 0; font-size: 12px; color: rgba(26,26,26,0.5);">
          ${tr ? `BTC Fiyatı: $${btcPrice.toLocaleString()} | Rapor oluşturuldu: ${date}` : `BTC Price: $${btcPrice.toLocaleString()} | Report generated at ${date}`}
        </p>
        <p style="margin: 8px 0 0 0; font-size: 11px; color: rgba(26,26,26,0.45);">
          ${tr ? 'Bu, mevcut ağ koşullarına dayanan bir tahmindir. Gerçek ücretler farklılık gösterebilir.' : 'This is an estimate based on current network conditions. Actual fees may vary.'}
        </p>
      </div>
    `;

    return report;
  };

  const exportAsPNG = async () => {
    if (!selectedEstimate) return;
    setIsExporting(true);
    try {
      const report = generateReportElement();
      document.body.appendChild(report);
      const canvas = await html2canvas(report, { backgroundColor: '#ffffff', scale: 2 });
      document.body.removeChild(report);
      const link = document.createElement('a');
      link.download = buildExportFilename({ en: 'bitcoin-fee-report', tr: 'bitcoin-ucret-raporu' }, 'png', language);
      link.href = canvas.toDataURL('image/png');
      link.click();
      toast({ title: tr ? 'Rapor dışa aktarıldı!' : 'Report exported!', description: tr ? 'Ücret raporunuz PNG olarak kaydedildi' : 'Your fee report has been saved as PNG' });
    } catch {
      toast({ title: tr ? 'Dışa aktarma başarısız' : 'Export failed', description: tr ? 'Rapor oluşturulamadı' : 'Could not generate the report', variant: 'destructive' });
    } finally {
      setIsExporting(false);
    }
  };

  const exportAsPDF = async () => {
    if (!selectedEstimate) return;
    setIsExporting(true);
    try {
      const report = generateReportElement();
      document.body.appendChild(report);
      const canvas = await html2canvas(report, { backgroundColor: '#ffffff', scale: 2 });
      document.body.removeChild(report);
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'landscape', unit: 'px', format: [canvas.width / 2, canvas.height / 2] });
      await applyLocalizedPdfFont(pdf, language);
      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
      pdf.save(buildExportFilename({ en: 'bitcoin-fee-report', tr: 'bitcoin-ucret-raporu' }, 'pdf', language));
      toast({ title: tr ? 'Rapor dışa aktarıldı!' : 'Report exported!', description: tr ? 'Ücret raporunuz PDF olarak kaydedildi' : 'Your fee report has been saved as PDF' });
    } catch {
      toast({ title: tr ? 'Dışa aktarma başarısız' : 'Export failed', description: tr ? 'Rapor oluşturulamadı' : 'Could not generate the report', variant: 'destructive' });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <ShareExportPanel
      actions={[
        { kind: 'pdf', onClick: exportAsPDF, loading: isExporting, disabled: !selectedEstimate },
        { kind: 'png', onClick: exportAsPNG, loading: isExporting, disabled: !selectedEstimate },
      ]}
    />
  );
};
