import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { HelpCircle } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

export const ProfitLossFAQSection = () => {
  const { language } = useLanguage();
  const tr = language==='tr';

  const faqs = tr ? [
    { question: 'Bitcoin kârımı nasıl hesaplarım?', answer: 'Bitcoin kârınızı hesaplamak için toplam gelirinizden (satış fiyatı × BTC miktarı − satım ücreti) toplam maliyetinizi (alış fiyatı + alım ücretleri) çıkarın. Bu hesap makinesi her alımı takip ederek, borsaya özgü ücretleri uygulayarak ve net kâr ya da zararınızı anında göstererek bu işlemi otomatikleştirir.' },
    { question: 'Bitcoin\'de maliyet bazı nedir?', answer: 'Maliyet bazı, işlem ücretleri dahil olmak üzere Bitcoin\'iniz için başlangıçta ödediğiniz toplam tutardır. Farklı fiyatlardan birden fazla alım yaptıysanız, ağırlıklı ortalama maliyet bazınız toplam yatırımınızın elde edilen toplam BTC\'ye bölünmesiyle hesaplanır. Bu, gerçek kâr veya zararınızı belirlemenin temelidir.' },
    { question: 'Borsa ücretleri Bitcoin kârımı nasıl etkiler?', answer: 'Borsa ücretleri her iki tarafta da kârınızı azaltır; hem alırken hem de satarken. Alım ücretleri yatırılan her dolar başına daha az BTC almanıza neden olurken, satım ücretleri toplam gelirinizi düşürür. Örneğin, Coinbase işlem başına yaklaşık %1,49 kesinti yapar; bu da 10.000 $ yatırımın her iki tarafta 149 $ ücret kaybetmesi anlamına gelir. Hesap makinemiz doğru sonuçlar için hem alım hem de satım ücretlerini hesaba katar.' },
    { question: 'Bitcoin için başabaş fiyatım nedir?', answer: 'Başabaş fiyatı, tüm ücretler dahil olmak üzere toplam yatırımınızı geri kazanmak için Bitcoin\'i satmanız gereken minimum fiyattır. Hesabı: Başabaş = Toplam Yatırım ÷ (Tutulan BTC × (1 − Satım Ücreti %)). Bu her zaman ortalama alış fiyatınızdan yüksektir çünkü işlem ücretleri de hesaba katılır.' },
    { question: 'Bitcoin\'de ROI nasıl hesaplanır?', answer: 'Bitcoin ROI (Yatırım Getirisi) şu şekilde hesaplanır: ROI = (Net Gelir − Toplam Yatırım) ÷ Toplam Yatırım × %100. Net gelir, satış fiyatı eksi satım ücretlerini içerir. Pozitif ROI kâr ettiğiniz, negatif ROI zarar ettiğiniz anlamına gelir. Hesap makinemiz hem brüt hem de net ROI\'yi gösterir.' },
    { question: 'Kripto kârını hesaplarken ücretleri hesaba katmalı mıyım?', answer: 'Kesinlikle. Pek çok yatırımcı ücretleri görmezden gelerek kârlarını fazla tahmin eder. Borsa ücretleri genellikle işlem başına %0,1 (Binance) ile %1,49 (Coinbase) arasında değişir. Coinbase ücretleriyle 10.000 $\'lık bir yatırımda toplam yaklaşık 300 $ ücret (alım + satım) ödersiniz; bu da doğrudan kârınızı düşürür.' },
    { question: 'Bu hesap makinesi vergi hesaplayıcısından ne farkı var?', answer: 'Bu Kâr/Zarar hesap makinesi, mevcut pozisyon değerinize ve olası satış sonuçlarınıza odaklanır. Vergi hesaplayıcısı (Sermaye Kazancı Vergisi Hesaplayıcımız gibi) ise elde tutma süresine, yargı yetkisine ve vergi dilimlerine göre vergi yükümlülüğünüzü belirler. Önce K/Z\'yi anlamak için bu aracı, ardından tahmini verginizi görmek için vergi hesaplayıcısını kullanın.' },
    { question: 'Birden fazla Bitcoin alımı için kâr hesaplayabilir miyim?', answer: 'Evet! Hesap makinemiz farklı fiyat ve miktarlarda birden fazla alımı destekler. Bu, dolar maliyet ortalaması yapıyor veya düşüşlerden alım yapıyorsanız doğru maliyet bazı hesabı için kritik öneme sahiptir. Her alım ayrı ayrı takip edilir ve toplam pozisyonunuz için ağırlıklı ortalama maliyet bazına dönüştürülür.' },
    { question: 'Ücretler sonrası Bitcoin kârı nasıl hesaplanır?', answer: 'Bitcoin kâr hesaplayıcımız Binance, Coinbase, Kraken ve daha fazlası için yerleşik borsa ücreti önayarları içerir. Borsa seçin veya özel ücret yüzdesi girin; hesap makinesinde gerçek net kârınızı görmek için tüm işlem maliyetlerinden hem alım hem de satım ücretleri düşülür.' },
    { question: 'Yatırımımı 10 katına çıkarmak için Bitcoin hangi fiyata ulaşmalı?', answer: '10x getiri için Bitcoin\'in ortalama giriş fiyatınızdan %900 yükselmesi gerekir (orijinalin %1000\'i = 10x). Ortalama girişiniz 30.000 $ ise, ücretler öncesinde BTC\'nin 300.000 $\'a ulaşması gerekir. %1-3 gidiş-dönüş ücret yükü ve %15-20 uzun vadeli sermaye kazancı vergisi hesaba katıldığında, 10x\'ten gerçek eve götürülen para yaklaşık 7,5-8x\'e düşer.' },
    { question: 'Gerçekleşmemiş Bitcoin kazançları vergilendirilebilir mi?', answer: 'Hayır. Gerçekleşmemiş kazançlar ABD, İngiltere, Kanada, Avustralya veya başlıca yargı bölgelerinin çoğunda vergilendirilemez. Yalnızca gerçekleşmiş bir kazanç tetiklediğinizde vergi ödersiniz; BTC\'yi fiat para karşılığı satmak, başka bir kriptoya takas etmek veya harcamak. Süresiz elinde tutmak hiçbir vergi yükümlülüğü oluşturmaz.' },
    { question: 'Bitcoin\'de brüt kâr ile net kâr arasındaki fark nedir?', answer: 'Brüt kâr, satış fiyatı eksi alış fiyatının basit hesabıdır. Net kâr, tüm ücretleri (alım ücreti, satım ücreti, ağ ücretleri, çekim ücretleri) düşer ve hesabınıza gerçekte yatılanı yansıtır. Fark, pozisyon büyüklüğünün %1-3\'ü kadar olabilir ve büyük işlemlerde önemli ölçüde birikebilinir.' },
    { question: 'FIFO - HIFO farkı Bitcoin kâr hesaplamasını nasıl etkiler?', answer: 'FIFO (ilk giren ilk çıkar) en eski, genellikle en ucuz coinlerinizi önce satar ve vergilendirilebilir kazancı en üst düzeye çıkarır. HIFO (en yüksek giren ilk çıkar) en pahalı lotunuzu önce satar ve her satışta vergiyi en aza indirir. IRS\'ye göre her ikisini de seçebilirsiniz, ancak vergi yılı içinde tutarlı olmanız gerekir.' },
    { question: 'Ağ ve çekim ücretlerini Bitcoin maliyet bazıma dahil etmeli miyim?', answer: 'Evet. Bitcoin\'inizi edinmek veya taşımakla doğrudan ilgili her türlü ücret maliyet bazına dahil edilir. Buna borsa alım ücretleri, kendi cüzdanınıza transferlerdeki ağ (madenci) ücretleri ve çekim ücretleri dahildir. Bunları doğru takip etmek, sonunda sattığınızda vergilendirilebilir kazancınızı azaltır.' },
    { question: 'Birden fazla alımım olduğunda Bitcoin kârını nasıl hesaplarım?', answer: 'Ağırlıklı ortalama maliyet bazını kullanın: Ücretler dahil yatırılan toplam dolar bölü tutulan toplam BTC. Yukarıdaki hesap makinesi birden fazla lot eklediğinizde bunu otomatik yapar. Vergi amaçları için FIFO, LIFO veya HIFO yöntemlerini kullanarak her lotu ayrı ayrı da takip edebilirsiniz.' },
    { question: 'Bitcoin\'de kâr ve zarar nasıl hesaplanır?', answer: 'Bitcoin\'de kâr ve zarar, satıştan elde ettiğiniz net gelir eksi toplam maliyet bazınızdır. Net gelir, satılan BTC\'nin satış fiyatıyla çarpımından borsa satım ücreti çıkarılarak hesaplanır. Maliyet bazı, alım ücretleri dahil olmak üzere o BTC\'yi edinmek için harcadığınız her doları kapsar. Yukarıdaki hesap makinesi her iki tarafı da dürüstçe tutar, böylece başlık rakamı hesabınıza gerçekte yatılanı yansıtır.' },
    { question: 'Kripto kâr ve zarar formülü nedir?', answer: 'Temiz formül şöyledir: K/Z = (Satış Fiyatı × Tutulan BTC × (1 − Satım Ücreti%)) − Toplam Yatırım. Toplam Yatırım rakamı alım ücretlerinde ödediğiniz tutarı zaten içerir, çünkü bu paralar hesabınızdan çıkmıştır. K/Z\'yi Toplam Yatırım\'a bölüp 100 ile çarparak ROI\'yi yüzde olarak elde edersiniz.' },
    { question: 'Bitcoin\'de başabaşı nasıl hesaplarım?', answer: 'Başabaş fiyatı, Toplam Yatırım bölü (Tutulan BTC × (1 − Satım Ücreti%)) formülüyle bulunur. %1,49 Coinbase ücreti ile 5.000 $\'lık bir alımda, ücretler sonrası yaklaşık 0,1372 BTC alırsınız. Bir de %1,49 satım ücreti ödeyerek 5.000 $\'ı geri kazanmak için BTC\'nin yaklaşık 36.995 $\'a ulaşması gerekir; bu, ortalama giriş fiyatınızın yaklaşık 995 $ üzerindedir. Yukarıdaki başabaş kartı siz yazarken bu hesabı canlı olarak yapar.' },
    { question: 'Bitcoin kârı üzerinden vergi öder miyim?', answer: 'ABD\'de evet, ancak yalnızca gerçekleşmiş kazançlar üzerinden. BTC\'yi fiat para için satmak, başka bir kriptoyla takas etmek veya harcamak vergilendirilebilir bir olay oluşturur. BTC\'yi süresiz tutmak hiçbir vergi yükümlülüğü oluşturmaz. Uzun vadeli elde tutmalar (365 günden fazla) gelire göre federal olarak %0, %15 veya %20 üzerinden vergilendirilir; kısa vadeli kazançlar ise olağan gelir olarak %37\'ye kadar vergilendirilebilir.' },
    { question: 'Borsa ücretleri Bitcoin kârını nasıl etkiler?', answer: 'Ücretler işlemin her iki tarafında da birikebilinir. Coinbase Standard her iki taraf için yaklaşık %1,49 kesinti yapar; bu da bir gidiş-dönüş maliyetinin BTC kıpırdamadan önce yaklaşık %2,98 olduğu anlamına gelir. Binance ve Bybit taraf başına %0,10 ücret alır; gidiş-dönüş %0,20\'dir. 10.000 $\'lık bir pozisyonda bu fark gerçek para olarak 278 $\'dır. Net durumunuzu görmek için yukarıdaki borsa ücreti önayarını kullanın.' },
    { question: 'Başabaşa ulaşmak için Bitcoin hangi fiyata ulaşmalı?', answer: 'Bu, ortalama giriş fiyatınıza ve satım ücretinize bağlıdır. %0,6 gidiş-dönüş Coinbase Advanced ücreti ile 63.800 $ ortalamayla 2024\'te alım yapan bir yatırımcının eşbaşa çıkmak için yaklaşık 64.565 $\'a ihtiyacı vardır. 92.400 $ ile 2025\'te alım yapan biri için bu rakam yaklaşık 93.508 $\'dır. Yukarıdaki başabaş kartı girdiğiniz lotlar ve ücretlere göre tam rakamı hesaplar.' },
    { question: 'Vergi için Bitcoin maliyet bazımı nasıl hesaplarım?', answer: 'ABD vergi amaçlarıyla maliyet bazınız, o BTC\'yi edinmek için ödediğiniz her doları (alış fiyatı + borsa alım ücreti + kendi cüzdanınıza gönderdiğiniz ağ ücretleri) içerir. Her lotu ayrı ayrı takip edin — Form 8949 satın alma tarihini ister. Satarken IRS FIFO, spesifik-lot ve HIFO seçmenize izin verir; yıl içinde tutarlı olduğunuz sürece. Yukarıdaki hesap makinesi ağırlıklı ortalama maliyet bazınızı canlı gösterir; bu, tahmini vergi yükümlülüğünüz için başlangıç noktasıdır.' },
    { question: 'Vergi indirimi için Bitcoin zararını nasıl hesaplarım?', answer: 'Zarar = Maliyet Bazı − Net Satış Geliri (satım ücretleri sonrası). Örneğin 8.000 $\'a 0,1 BTC alıp 5.000 $\'a sattığınızda ve %0,5 ücret ödediğinizde net gelir 4.975 $, gerçekleşmiş zarar 3.025 $\'dır. ABD\'de bu zararı önce sermaye kazançlarını netlemek için kullanabilir, ardından yılda 3.000 $\'a kadar olağan gelirden düşebilir ve kalanı ileri taşıyabilirsiniz. 30 gün içinde aynı BTC\'yi geri alma "wash-sale" kuralı 2025 itibarıyla ABD\'de kripto için hâlâ geçerli değildir; ancak durum değişebilir; her zaman güncel IRS rehberini kontrol edin.' },
    { question: 'Bitcoin ROI grafiği nasıl okunur?', answer: 'Yatay eksen zamanı, dikey eksen ise ortalama giriş fiyatınıza göre yüzde getiriyi gösterir. Sıfır çizgisi başabaştır (ücretler sonrası). Sıfırın üstündeki her nokta kârda olduğunuzu, altındaki her nokta zararda olduğunuzu gösterir. Dik yukarı eğim hızlı bir kâr yığılmasıdır; uzun yatay bölge fiyat sıkışmasıdır. Yukarıdaki hesap makinesindeki ROI çizgisi ücret sonrası net rakamı kullanır, böylece "5.000 $ kâr" göründüğünde bu gerçekten hesabınıza gelecek olan tutardır.' },
  ];
    { question: 'How do I calculate my Bitcoin profit?', answer: 'To calculate your Bitcoin profit, subtract your total cost (purchase price + buy fees) from your total proceeds (sell price × BTC amount - sell fees). This calculator automates this by tracking each purchase, applying exchange-specific fees, and showing your net profit or loss instantly.' },
    { question: 'What is cost basis in Bitcoin?', answer: 'Cost basis is the total amount you originally paid for your Bitcoin, including any transaction fees. If you made multiple purchases at different prices, your weighted average cost basis is calculated by dividing your total investment by the total BTC acquired. This is essential for determining your true profit or loss.' },
    { question: 'How do exchange fees affect my Bitcoin profit?', answer: "Exchange fees reduce your profit on both ends — when you buy and when you sell. Buy fees mean you receive less BTC per dollar invested, and sell fees reduce your total proceeds. For example, Coinbase charges ~1.49% per trade, meaning a $10,000 investment loses $149 to fees on each side. Our calculator factors in both buy and sell fees for accurate results." },
    { question: 'What is my breakeven price for Bitcoin?', answer: "Your breakeven price is the minimum price at which you need to sell your Bitcoin to recover your total investment including all fees. It's calculated as: Breakeven = Total Invested ÷ (BTC Held × (1 - Sell Fee %)). This is always higher than your average purchase price because of trading fees." },
    { question: 'How do I calculate ROI on Bitcoin?', answer: 'Bitcoin ROI (Return on Investment) is calculated as: ROI = (Net Proceeds - Total Invested) ÷ Total Invested × 100%. Net proceeds account for the sell price minus sell fees. A positive ROI means you made a profit, while negative means a loss. Our calculator shows both gross and net ROI.' },
    { question: 'Should I account for fees when calculating crypto profit?', answer: "Absolutely. Many traders overlook fees and overestimate their profits. Exchange fees typically range from 0.1% (Binance) to 1.49% (Coinbase) per trade. On a $10,000 investment with Coinbase fees, you'd pay ~$300 in total fees (buy + sell), which directly reduces your profit." },
    { question: 'How does this calculator differ from a tax calculator?', answer: "This Profit/Loss calculator focuses on your current position value and potential sell outcomes. A tax calculator (like our Capital Gains Tax Calculator) determines your tax liability based on holding period, jurisdiction, and tax brackets. Use this tool first to understand your P/L, then the tax calculator to estimate what you'd owe." },
    { question: 'Can I calculate profit for multiple Bitcoin purchases?', answer: "Yes! Our calculator supports multiple purchases at different prices and amounts. This is crucial for accurate cost basis calculation if you've been dollar-cost averaging or buying dips. Each purchase is tracked individually, then combined into a weighted average cost basis for your total position." },
    { question: 'How do I calculate Bitcoin profit after fees?', answer: 'Our Bitcoin profit calculator includes built-in exchange fee presets for Binance, Coinbase, Kraken, and more. Select your exchange or enter custom fee percentages — the calculator deducts fees from both buy and sides to show your true net profit after all transaction costs.' },
    { question: 'What price does Bitcoin need to hit for me to 10x my investment?', answer: 'For a 10x return, Bitcoin needs to rise 900% from your average entry price (1000% of original = 10x). If your average entry was $30,000, BTC needs to reach $300,000 before fees. Factor in a 1-3% round-trip fee load and 15-20% long-term capital gains tax, and your real take-home from a 10x is closer to 7.5-8x.' },
    { question: 'Are unrealized Bitcoin gains taxable?', answer: 'No. Unrealized gains are not taxable in the US, UK, Canada, Australia, or most major jurisdictions. You only owe tax when you trigger a realized gain — selling BTC for fiat, swapping it for another crypto, or spending it. Holding indefinitely creates no tax liability.' },
    { question: 'What is the difference between gross profit and net profit on Bitcoin?', answer: 'Gross profit is the simple sell price minus buy price calculation. Net profit deducts all fees (buy fee, sell fee, network fees, withdrawal fees) and reflects what actually lands in your account. The difference can be 1-3% of position size, which compounds significantly on large trades.' },
    { question: 'How does FIFO vs HIFO change my Bitcoin profit calculation?', answer: 'FIFO (first in, first out) sells your oldest, often cheapest coins first, maximizing taxable gains. HIFO (highest in, first out) sells your most expensive lot first, minimizing tax on each sale. The IRS allows you to choose, but you must be consistent within a tax year.' },
    { question: 'Should I count network and withdrawal fees in my Bitcoin cost basis?', answer: 'Yes. Any fee directly tied to acquiring or moving your Bitcoin counts toward cost basis. This includes exchange buy fees, network (miner) fees on transfers to your own wallet, and withdrawal fees. Tracking these accurately reduces your taxable gain when you eventually sell.' },
    { question: 'How do I calculate Bitcoin profit when I have multiple purchases?', answer: 'Use a weighted average cost basis: total dollars invested (including fees) divided by total BTC held. The calculator above does this automatically when you add multiple lots. For tax purposes, you can also track each lot individually using FIFO, LIFO, or HIFO methods.' },
    { question: 'How is profit and loss calculated on Bitcoin?', answer: 'Profit and loss on Bitcoin is your net proceeds from a sale minus your total cost basis. Net proceeds equal your sell price multiplied by the BTC sold, minus the exchange sell fee. Cost basis equals every dollar you spent acquiring that BTC, including buy fees. The calculator above keeps both sides honest so the headline number reflects what actually lands in your account.' },
    { question: 'What is the formula for crypto profit and loss?', answer: 'The clean formula is: P/L = (Sell Price × BTC Held × (1 − Sell Fee%)) − Total Invested. The Total Invested figure already includes whatever you paid in buy fees, since those dollars left your account. Divide P/L by Total Invested and multiply by 100 to get ROI as a percentage.' },
    { question: 'How do I calculate break-even on Bitcoin?', answer: 'Break-even price equals Total Invested divided by (BTC Held × (1 − Sell Fee%)). On a $5,000 buy at 1.49% Coinbase fees, you receive about 0.1372 BTC after fees. To recover the full $5,000 with another 1.49% sell fee, BTC must reach roughly $36,995, which is about $995 above your average entry price. The break-even card above runs this math live as you type.' },
    { question: 'Do I pay tax on Bitcoin profit?', answer: 'In the US, yes, but only on realized gains. Selling BTC for fiat, swapping it for another crypto, or spending it all trigger a taxable event. Holding BTC indefinitely creates no tax liability. Long-term holds (over 365 days) are taxed at 0, 15, or 20 percent federally based on income, plus a possible 3.8 percent NIIT. Short-term gains are taxed as ordinary income up to 37 percent.' },
    { question: 'How do exchange fees affect Bitcoin profit?', answer: 'Fees compound on both sides of the trade. Coinbase Standard charges roughly 1.49 percent per side, so a round-trip costs about 2.98 percent before BTC moves a dollar. Binance and Bybit charge 0.10 percent per side, for a 0.20 percent round-trip. On a $10,000 position, that gap is $278 in real money. Use the exchange fee preset above to see your true net.' },
    { question: 'What price does Bitcoin need to reach for me to break even?', answer: 'It depends on your average entry price and your sell fee. A 2024 buyer with a $63,800 average and 0.6 percent round-trip Coinbase Advanced fees needs roughly $64,565 to walk away even. A 2025 buyer at $92,400 needs about $93,508. The break-even card above calculates your exact number based on the lots and fees you entered.' },
  ];

  return (
    <section className="py-20 bg-muted/30">
      <div className="container mx-auto px-6 max-w-4xl">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 border border-primary/30 rounded-full px-4 py-1.5 text-sm font-medium text-primary mb-6">
            <HelpCircle className="w-4 h-4" />
            {tr?'SSS':'FAQ'}
          </div>
          <h2 className="text-h2 font-bold mb-4 text-foreground">
            {tr?'Sıkça Sorulan Sorular':'Frequently Asked Questions'}
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            {tr?'Bitcoin kâr ve zarar hesaplaması hakkında bilmeniz gereken her şey':'Everything you need to know about calculating Bitcoin profit and loss'}
          </p>
        </div>

        <Accordion type="single" collapsible className="space-y-4">
          {faqs.map((faq, index) => (
            <AccordionItem key={index} value={`item-${index}`} className="bg-card border border-border/50 rounded-xl px-6">
              <AccordionTrigger className="text-left font-medium text-foreground hover:text-primary py-5 text-base">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground pb-5 text-sm leading-relaxed">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
};
