// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-bitcoin-price.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var get_bitcoin_price_default = defineTool({
  name: "get_bitcoin_price",
  title: "Get current Bitcoin price",
  description: "Returns the current Bitcoin (BTC) spot price in USD (and optionally other fiat currencies) with 24-hour change. Sourced live from CoinGecko.",
  inputSchema: {
    currencies: z.array(z.string().min(2).max(6)).max(6).optional().describe(
      "Optional list of fiat currency codes (e.g. ['usd','eur','gbp','try']). Defaults to ['usd']."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ currencies }) => {
    const vs = (currencies && currencies.length ? currencies : ["usd"]).map((c) => c.toLowerCase()).join(",");
    const url = `https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=${vs}&include_24hr_change=true&include_market_cap=true`;
    try {
      const res = await fetch(url, { headers: { accept: "application/json" } });
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `CoinGecko error: HTTP ${res.status}` }],
          isError: true
        };
      }
      const raw = await res.json();
      const btc = raw.bitcoin ?? {};
      const prices = {};
      for (const c of vs.split(",")) {
        const price = btc[c];
        if (typeof price !== "number") continue;
        prices[c] = {
          price,
          change_24h_pct: btc[`${c}_24h_change`] ?? null,
          market_cap: btc[`${c}_market_cap`] ?? null
        };
      }
      const summary = Object.entries(prices).map(([c, v]) => `${c.toUpperCase()}: ${v.price.toLocaleString()} (${v.change_24h_pct?.toFixed(2) ?? "?"}% 24h)`).join(" \xB7 ");
      return {
        content: [{ type: "text", text: `BTC \u2014 ${summary}` }],
        structuredContent: { source: "coingecko", timestamp: (/* @__PURE__ */ new Date()).toISOString(), prices }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Failed to fetch price: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/calculate-what-if.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var calculate_what_if_default = defineTool2({
  name: "calculate_bitcoin_what_if",
  title: "Bitcoin what-if investment",
  description: "Given a past investment date and USD amount, returns what that investment in Bitcoin would be worth today, including BTC amount, current value, gain/loss, and multiple.",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Investment date in YYYY-MM-DD format. Bitcoin history is available from 2013-04-28 onward."),
    usd_amount: z2.number().positive().describe("Amount invested in USD on that date.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ date, usd_amount }) => {
    const [y, m, d] = date.split("-");
    const cgDate = `${d}-${m}-${y}`;
    try {
      const [histRes, curRes] = await Promise.all([
        fetch(`https://api.coingecko.com/api/v3/coins/bitcoin/history?date=${cgDate}&localization=false`, {
          headers: { accept: "application/json" }
        }),
        fetch(`https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd`, {
          headers: { accept: "application/json" }
        })
      ]);
      if (!histRes.ok || !curRes.ok) {
        return {
          content: [{ type: "text", text: `Price API error: hist=${histRes.status}, current=${curRes.status}` }],
          isError: true
        };
      }
      const hist = await histRes.json();
      const cur = await curRes.json();
      const priceThen = hist.market_data?.current_price?.usd;
      const priceNow = cur.bitcoin?.usd;
      if (!priceThen || !priceNow) {
        return {
          content: [{ type: "text", text: `No price available for ${date}. Bitcoin market data starts 2013-04-28.` }],
          isError: true
        };
      }
      const btc = usd_amount / priceThen;
      const valueNow = btc * priceNow;
      const gain = valueNow - usd_amount;
      const multiple = valueNow / usd_amount;
      const summary = `$${usd_amount.toLocaleString()} on ${date} bought ${btc.toFixed(6)} BTC @ $${priceThen.toLocaleString()}. Today: $${valueNow.toLocaleString(void 0, { maximumFractionDigits: 2 })} (${multiple.toFixed(2)}\xD7, ${gain >= 0 ? "+" : ""}$${gain.toLocaleString(void 0, { maximumFractionDigits: 2 })}).`;
      return {
        content: [{ type: "text", text: summary }],
        structuredContent: {
          date,
          usd_invested: usd_amount,
          price_then_usd: priceThen,
          price_now_usd: priceNow,
          btc_acquired: btc,
          value_now_usd: valueNow,
          gain_usd: gain,
          multiple
        }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Failed: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/calculate-profit-loss.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var calculate_profit_loss_default = defineTool3({
  name: "calculate_bitcoin_profit_loss",
  title: "Bitcoin profit/loss",
  description: "Calculate profit or loss on a Bitcoin trade from buy price, sell price, and amount. Returns absolute P/L, percentage return, and total invested/sold values.",
  inputSchema: {
    buy_price_usd: z3.number().positive().describe("Purchase price per BTC in USD."),
    sell_price_usd: z3.number().positive().describe("Sell (or current) price per BTC in USD."),
    btc_amount: z3.number().positive().describe("Amount of BTC in the position."),
    fee_pct: z3.number().min(0).max(10).optional().describe("Optional round-trip fee percentage (e.g. 0.5 for 0.5%).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ buy_price_usd, sell_price_usd, btc_amount, fee_pct }) => {
    const invested = buy_price_usd * btc_amount;
    const gross = sell_price_usd * btc_amount;
    const fees = (fee_pct ?? 0) / 100 * (invested + gross);
    const net = gross - invested - fees;
    const pct = net / invested * 100;
    return {
      content: [
        {
          type: "text",
          text: `Invested $${invested.toLocaleString()} \xB7 Sold $${gross.toLocaleString()} \xB7 Fees $${fees.toLocaleString(void 0, { maximumFractionDigits: 2 })} \xB7 Net ${net >= 0 ? "+" : ""}$${net.toLocaleString(void 0, { maximumFractionDigits: 2 })} (${pct.toFixed(2)}%)`
        }
      ],
      structuredContent: {
        invested_usd: invested,
        gross_usd: gross,
        fees_usd: fees,
        net_profit_usd: net,
        return_pct: pct
      }
    };
  }
});

// src/lib/mcp/tools/simulate-dca.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var simulate_dca_default = defineTool4({
  name: "simulate_bitcoin_dca",
  title: "Bitcoin DCA simulation",
  description: "Simulate a Dollar-Cost-Averaging strategy: buy a fixed USD amount of BTC on a regular cadence between two dates. Returns total invested, BTC accumulated, current value, and ROI.",
  inputSchema: {
    start_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Start date YYYY-MM-DD (>= 2013-04-28)."),
    end_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("End date YYYY-MM-DD. Defaults to today."),
    usd_per_purchase: z4.number().positive().describe("USD amount to buy each period."),
    cadence_days: z4.number().int().min(1).max(90).default(7).describe("Days between purchases. Default 7 (weekly).")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ start_date, end_date, usd_per_purchase, cadence_days }) => {
    const start = (/* @__PURE__ */ new Date(`${start_date}T00:00:00Z`)).getTime();
    const end = end_date ? (/* @__PURE__ */ new Date(`${end_date}T00:00:00Z`)).getTime() : Date.now();
    if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start) {
      return { content: [{ type: "text", text: "Invalid date range." }], isError: true };
    }
    const from = Math.floor(start / 1e3);
    const to = Math.floor(end / 1e3);
    try {
      const url = `https://api.coingecko.com/api/v3/coins/bitcoin/market_chart/range?vs_currency=usd&from=${from}&to=${to}`;
      const res = await fetch(url, { headers: { accept: "application/json" } });
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `CoinGecko error: HTTP ${res.status}` }],
          isError: true
        };
      }
      const raw = await res.json();
      const prices = raw.prices ?? [];
      if (!prices.length) {
        return { content: [{ type: "text", text: "No price data in range." }], isError: true };
      }
      const dailies = /* @__PURE__ */ new Map();
      for (const [ts, p] of prices) {
        const d = new Date(ts).toISOString().slice(0, 10);
        dailies.set(d, p);
      }
      const ordered = [...dailies.entries()].sort();
      let totalUsd = 0;
      let totalBtc = 0;
      let purchases = 0;
      let lastBuyTs = -Infinity;
      const oneDayMs = 864e5;
      for (const [d, price] of ordered) {
        const ts = (/* @__PURE__ */ new Date(`${d}T00:00:00Z`)).getTime();
        if (ts - lastBuyTs >= cadence_days * oneDayMs) {
          totalUsd += usd_per_purchase;
          totalBtc += usd_per_purchase / price;
          purchases += 1;
          lastBuyTs = ts;
        }
      }
      const lastPrice = ordered[ordered.length - 1][1];
      const value = totalBtc * lastPrice;
      const roiPct = (value - totalUsd) / totalUsd * 100;
      return {
        content: [
          {
            type: "text",
            text: `${purchases} purchases \xB7 $${totalUsd.toLocaleString()} invested \u2192 ${totalBtc.toFixed(6)} BTC worth $${value.toLocaleString(void 0, { maximumFractionDigits: 2 })} (${roiPct >= 0 ? "+" : ""}${roiPct.toFixed(1)}% ROI)`
          }
        ],
        structuredContent: {
          purchases,
          total_invested_usd: totalUsd,
          total_btc: totalBtc,
          current_price_usd: lastPrice,
          current_value_usd: value,
          roi_pct: roiPct,
          cadence_days
        }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Failed: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/convert-bitcoin.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var convert_bitcoin_default = defineTool5({
  name: "convert_bitcoin",
  title: "Bitcoin/fiat converter",
  description: "Convert between BTC (or satoshis) and USD (or another fiat) at the current market price. Provide EITHER btc/sats OR fiat_amount, not both.",
  inputSchema: {
    btc: z5.number().positive().optional().describe("Amount in BTC to convert TO fiat."),
    sats: z5.number().positive().optional().describe("Amount in satoshis (1 BTC = 100,000,000 sats) to convert TO fiat."),
    fiat_amount: z5.number().positive().optional().describe("Amount in fiat to convert TO BTC."),
    fiat: z5.string().min(2).max(6).default("usd").describe("Fiat currency code, e.g. 'usd', 'eur', 'try'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ btc, sats, fiat_amount, fiat }) => {
    const provided = [btc, sats, fiat_amount].filter((v) => v !== void 0).length;
    if (provided !== 1) {
      return {
        content: [{ type: "text", text: "Provide exactly one of: btc, sats, fiat_amount." }],
        isError: true
      };
    }
    const cur = fiat.toLowerCase();
    try {
      const res = await fetch(
        `https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=${cur}`,
        { headers: { accept: "application/json" } }
      );
      if (!res.ok) {
        return { content: [{ type: "text", text: `Price API HTTP ${res.status}` }], isError: true };
      }
      const raw = await res.json();
      const rate = raw.bitcoin?.[cur];
      if (!rate) {
        return { content: [{ type: "text", text: `No rate for BTC/${cur.toUpperCase()}.` }], isError: true };
      }
      let btcAmount;
      if (btc !== void 0) btcAmount = btc;
      else if (sats !== void 0) btcAmount = sats / 1e8;
      else btcAmount = fiat_amount / rate;
      const fiatValue = btcAmount * rate;
      return {
        content: [
          {
            type: "text",
            text: `${btcAmount.toFixed(8)} BTC = ${fiatValue.toLocaleString(void 0, { maximumFractionDigits: 2 })} ${cur.toUpperCase()} @ ${rate.toLocaleString()} ${cur.toUpperCase()}/BTC`
          }
        ],
        structuredContent: {
          btc: btcAmount,
          sats: Math.round(btcAmount * 1e8),
          fiat: cur,
          fiat_value: fiatValue,
          rate
        }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Failed: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-halving-countdown.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_halving_countdown_default = defineTool6({
  name: "get_bitcoin_halving_countdown",
  title: "Bitcoin halving countdown",
  description: "Returns the current block height, next halving block, estimated days until the next halving, and post-halving block subsidy.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async () => {
    try {
      const res = await fetch("https://mempool.space/api/blocks/tip/height");
      if (!res.ok) {
        return { content: [{ type: "text", text: `mempool.space HTTP ${res.status}` }], isError: true };
      }
      const height = Number(await res.text());
      if (!Number.isFinite(height)) {
        return { content: [{ type: "text", text: "Unexpected height response." }], isError: true };
      }
      const HALVING_INTERVAL = 21e4;
      const halvingsPassed = Math.floor(height / HALVING_INTERVAL);
      const nextHalvingBlock = (halvingsPassed + 1) * HALVING_INTERVAL;
      const blocksLeft = nextHalvingBlock - height;
      const minutesLeft = blocksLeft * 10;
      const days = minutesLeft / 60 / 24;
      const eta = new Date(Date.now() + minutesLeft * 6e4);
      const nextSubsidy = 50 / Math.pow(2, halvingsPassed + 1);
      return {
        content: [
          {
            type: "text",
            text: `Block ${height.toLocaleString()}. Next halving at block ${nextHalvingBlock.toLocaleString()} in ~${blocksLeft.toLocaleString()} blocks (~${days.toFixed(1)} days, ETA ${eta.toISOString().slice(0, 10)}). Subsidy after halving: ${nextSubsidy} BTC/block.`
          }
        ],
        structuredContent: {
          current_block: height,
          next_halving_block: nextHalvingBlock,
          blocks_remaining: blocksLeft,
          estimated_days: days,
          estimated_date_iso: eta.toISOString(),
          next_block_subsidy_btc: nextSubsidy,
          halvings_passed: halvingsPassed
        }
      };
    } catch (err) {
      return { content: [{ type: "text", text: `Failed: ${err.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "fyquklzfhkeiybhdnccb";
var mcp_default = defineMcp({
  name: "bitcoin-calculator-tools",
  title: "Bitcoin Calculator Tools",
  version: "0.1.0",
  instructions: "Bitcoin calculators and live market data from bitcoincalculator.tools. Use `get_bitcoin_price` for the current BTC spot price, `convert_bitcoin` for BTC\u2194fiat conversions, `calculate_bitcoin_what_if` to see what a past USD investment would be worth today, `simulate_bitcoin_dca` for a dollar-cost-averaging backtest, `calculate_bitcoin_profit_loss` for pure P/L math on a trade, and `get_bitcoin_halving_countdown` for the next halving ETA. All tools are read-only; prices are sourced from CoinGecko and mempool.space.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_bitcoin_price_default,
    convert_bitcoin_default,
    calculate_what_if_default,
    simulate_dca_default,
    calculate_profit_loss_default,
    get_halving_countdown_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
