// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-bitcoin-price.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var get_bitcoin_price_default = defineTool({
  name: "get_bitcoin_price",
  title: "Get Bitcoin price",
  description: "Fetch the current Bitcoin (BTC) spot price in the requested fiat currency (USD, EUR, GBP, TRY, JPY, etc.).",
  inputSchema: {
    currency: z.string().trim().min(3).max(4).describe("ISO fiat currency code, e.g. 'USD', 'EUR', 'GBP', 'TRY'.").default("USD")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ currency }) => {
    const cur = (currency || "USD").toUpperCase();
    const url = `https://fyquklzfhkeiybhdnccb.supabase.co/functions/v1/price-proxy?vs=${encodeURIComponent(
      cur.toLowerCase()
    )}`;
    try {
      const res = await fetch(url, { headers: { accept: "application/json" } });
      if (!res.ok) {
        return {
          content: [
            { type: "text", text: `Price proxy returned HTTP ${res.status}` }
          ],
          isError: true
        };
      }
      const data = await res.json();
      const price = data?.bitcoin?.[cur.toLowerCase()] ?? data[cur.toLowerCase()] ?? data.price;
      if (typeof price !== "number") {
        return {
          content: [
            {
              type: "text",
              text: `Could not parse price for ${cur} from response: ${JSON.stringify(data).slice(0, 300)}`
            }
          ],
          isError: true
        };
      }
      return {
        content: [
          {
            type: "text",
            text: `1 BTC \u2248 ${price.toLocaleString("en-US", { maximumFractionDigits: 2 })} ${cur}`
          }
        ],
        structuredContent: { currency: cur, price, source: "price-proxy" }
      };
    } catch (err) {
      return {
        content: [
          {
            type: "text",
            text: `Failed to fetch price: ${err.message}`
          }
        ],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/convert-bitcoin.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var convert_bitcoin_default = defineTool2({
  name: "convert_bitcoin",
  title: "Convert Bitcoin \u2194 fiat / sats",
  description: "Convert an amount between BTC, satoshis (sats), and a fiat currency using the live spot price.",
  inputSchema: {
    amount: z2.number().positive().describe("Amount to convert."),
    from: z2.enum(["BTC", "SATS", "FIAT"]).describe("Unit of the input amount."),
    to: z2.enum(["BTC", "SATS", "FIAT"]).describe("Unit to convert to."),
    currency: z2.string().trim().min(3).max(4).default("USD").describe("Fiat currency code used when 'from' or 'to' is 'FIAT'.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ amount, from, to, currency }) => {
    const cur = (currency || "USD").toUpperCase();
    const priceUrl = `https://fyquklzfhkeiybhdnccb.supabase.co/functions/v1/price-proxy?vs=${cur.toLowerCase()}`;
    let price = null;
    try {
      const res = await fetch(priceUrl);
      if (res.ok) {
        const data = await res.json();
        price = data?.bitcoin?.[cur.toLowerCase()] ?? data[cur.toLowerCase()] ?? data.price ?? null;
      }
    } catch {
    }
    if (from !== to && (from === "FIAT" || to === "FIAT") && !price) {
      return {
        content: [
          { type: "text", text: "Could not fetch live BTC price for conversion." }
        ],
        isError: true
      };
    }
    let btc;
    if (from === "BTC") btc = amount;
    else if (from === "SATS") btc = amount / 1e8;
    else btc = amount / price;
    let output;
    let unit;
    if (to === "BTC") {
      output = btc;
      unit = "BTC";
    } else if (to === "SATS") {
      output = Math.round(btc * 1e8);
      unit = "sats";
    } else {
      output = btc * price;
      unit = cur;
    }
    const formatted = to === "SATS" ? `${output.toLocaleString("en-US")} sats` : `${output.toLocaleString("en-US", { maximumFractionDigits: to === "BTC" ? 8 : 2 })} ${unit}`;
    return {
      content: [
        {
          type: "text",
          text: `${amount} ${from === "FIAT" ? cur : from} = ${formatted}`
        }
      ],
      structuredContent: {
        input: { amount, from, currency: cur },
        output: { value: output, unit },
        spot_price: price
      }
    };
  }
});

// src/lib/mcp/tools/simulate-dca.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var simulate_dca_default = defineTool3({
  name: "simulate_dca",
  title: "Simulate Bitcoin DCA",
  description: "Estimate the outcome of a Bitcoin dollar-cost-averaging plan: total invested, BTC accumulated, and current value at the live spot price.",
  inputSchema: {
    contribution: z3.number().positive().describe("Amount contributed each period."),
    frequency: z3.enum(["daily", "weekly", "monthly"]).default("monthly").describe("Contribution frequency."),
    years: z3.number().positive().max(50).describe("Number of years to run the plan."),
    currency: z3.string().trim().min(3).max(4).default("USD").describe("Fiat currency of the contribution.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ contribution, frequency, years, currency }) => {
    const cur = currency.toUpperCase();
    const periodsPerYear = frequency === "daily" ? 365 : frequency === "weekly" ? 52 : 12;
    const periods = Math.round(years * periodsPerYear);
    const totalInvested = contribution * periods;
    let price = null;
    try {
      const res = await fetch(
        `https://fyquklzfhkeiybhdnccb.supabase.co/functions/v1/price-proxy?vs=${cur.toLowerCase()}`
      );
      if (res.ok) {
        const data = await res.json();
        price = data?.bitcoin?.[cur.toLowerCase()] ?? data[cur.toLowerCase()] ?? null;
      }
    } catch {
    }
    if (!price) {
      return {
        content: [
          { type: "text", text: "Could not fetch BTC price for the projection." }
        ],
        isError: true
      };
    }
    const btcAccumulated = totalInvested / price;
    const currentValue = btcAccumulated * price;
    const roi = (currentValue - totalInvested) / totalInvested * 100;
    const fmt = (n, d = 2) => n.toLocaleString("en-US", { maximumFractionDigits: d });
    return {
      content: [
        {
          type: "text",
          text: `DCA plan: ${fmt(contribution)} ${cur} ${frequency} for ${years} years (${periods} contributions)
Total invested: ${fmt(totalInvested)} ${cur}
BTC accumulated (at flat ${fmt(price)} ${cur}/BTC): ${fmt(btcAccumulated, 8)} BTC
Current value: ${fmt(currentValue)} ${cur} (ROI ${fmt(roi)}%)
Note: assumes constant price. For a historical backtest, use the DCA calculator on the site.`
        }
      ],
      structuredContent: {
        contribution,
        frequency,
        years,
        periods,
        currency: cur,
        total_invested: totalInvested,
        btc_accumulated: btcAccumulated,
        spot_price: price,
        current_value: currentValue,
        roi_percent: roi
      }
    };
  }
});

// src/lib/mcp/tools/list-calculators.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var CALCULATORS = [
  { name: "Bitcoin Converter", slug: "bitcoin-converter", description: "BTC \u2194 sats \u2194 fiat converter." },
  { name: "Bitcoin DCA Calculator", slug: "bitcoin-dca-calculator", description: "Backtest dollar-cost-averaging into BTC." },
  { name: "Bitcoin Profit / Loss", slug: "bitcoin-profit-loss-calculator", description: "P&L from a BTC buy at price X and sell at price Y." },
  { name: "Bitcoin Retirement", slug: "bitcoin-retirement-calculator", description: "FIRE and retirement planning around a BTC nest egg." },
  { name: "Bitcoin Investment Calculator", slug: "bitcoin-investment-calculator", description: "Growth projection for a lump-sum BTC investment." },
  { name: "Bitcoin Savings Calculator", slug: "bitcoin-savings-calculator", description: "Compare BTC vs fiat savings growth." },
  { name: "Bitcoin Capital Gains Tax", slug: "bitcoin-capital-gains-tax-calculator", description: "Generic BTC capital-gains estimator." },
  { name: "Bitcoin UK CGT", slug: "bitcoin-uk-cgt-calculator", description: "UK Capital Gains Tax estimator for BTC." },
  { name: "Bitcoin Germany Tax", slug: "bitcoin-germany-tax-calculator", description: "Germany BTC tax estimator (1-year rule)." },
  { name: "Bitcoin India Tax", slug: "bitcoin-india-tax-calculator", description: "India 30% VDA tax estimator." },
  { name: "Bitcoin Mining Profitability", slug: "bitcoin-mining-profitability-calculator", description: "Mining P&L given hashrate, power cost, difficulty." },
  { name: "Bitcoin Halving Countdown", slug: "bitcoin-halving-countdown", description: "Time until the next Bitcoin halving." },
  { name: "Bitcoin Fear & Greed", slug: "bitcoin-fear-greed-index", description: "Current market sentiment index." },
  { name: "Bitcoin Rainbow Chart", slug: "bitcoin-rainbow-chart", description: "Long-term price valuation band chart." },
  { name: "Bitcoin Purchasing Power", slug: "bitcoin-purchasing-power-calculator", description: "What USD purchasing power your BTC represents." },
  { name: "Bitcoin Pizza Day", slug: "bitcoin-pizza-day-calculator", description: "Value today of the 10 000 BTC pizza purchase." }
];
var BASE_URL = "https://bitcoincalculatortoolz.lovable.app";
var list_calculators_default = defineTool4({
  name: "list_calculators",
  title: "List calculators",
  description: "List available Bitcoin calculators on the site with descriptions and public URLs. Supports optional keyword filtering.",
  inputSchema: {
    query: z4.string().trim().optional().describe("Optional case-insensitive substring to filter by name/description."),
    lang: z4.enum(["en", "tr"]).default("en").describe("Language variant for the returned URLs (English or Turkish).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ query, lang }) => {
    const q = query?.toLowerCase();
    const items = CALCULATORS.filter(
      (c) => !q || c.name.toLowerCase().includes(q) || c.description.toLowerCase().includes(q) || c.slug.includes(q)
    ).map((c) => ({
      ...c,
      url: lang === "tr" ? `${BASE_URL}/tr/${c.slug}` : `${BASE_URL}/${c.slug}`
    }));
    const text = items.length ? items.map((c) => `\u2022 ${c.name} \u2014 ${c.description}
  ${c.url}`).join("\n") : "No calculators matched that query.";
    return {
      content: [{ type: "text", text }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bitcoin-calculator-toolz-mcp",
  title: "Bitcoin Calculator Toolz MCP",
  version: "0.1.0",
  instructions: "Tools for Bitcoin Calculator Toolz. Fetch the live BTC spot price, convert between BTC / sats / fiat, run a quick DCA projection, and browse the site's calculator catalog with deep links (EN or TR).",
  tools: [get_bitcoin_price_default, convert_bitcoin_default, simulate_dca_default, list_calculators_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
