INSERT INTO public.affiliates (id,name,category,tier,priority,enabled,url_en,url_tr,target_pages,target_results,language_restriction,conversion_intent,commission_rate,commission_currency,cookie_days,default_format)
VALUES
('ledger','Ledger','hardware-wallet',1,9,true,'https://shop.ledger.com/pages/ledger-nano-s-plus/?r=8c4e8e87cac7','https://shop.ledger.com/pages/ledger-nano-s-plus/?r=8c4e8e87cac7',ARRAY['accumulation-score','retirement','wealth-percentile','hodl-strategy','bitcoin-savings','inheritance-tax','btc-vs-real-estate']::text[],ARRAY['high-value','long-term','profit','accumulation','security']::text[],ARRAY[]::text[],'high',10,'USD',30,'image-banner'),
('koinly','Koinly','tax',1,9,true,'https://koinly.io/?via=0481A637&utm_source=affiliate','https://koinly.io/?via=0481A637&utm_source=affiliate',ARRAY['capital-gains-tax','profit-loss','inheritance-tax','zakat','dca','investment','hodl-strategy','average-buy-price']::text[],ARRAY['profit','tax-relevant']::text[],ARRAY[]::text[],'high',25,'USD',30,NULL),
('coinbase','Coinbase','exchange',1,8,true,'https://coinbase-consumer.sjv.io/c/7283174/3383210/9251','https://coinbase-consumer.sjv.io/c/7283174/3383210/9251',ARRAY['*']::text[],ARRAY['*']::text[],ARRAY[]::text[],'high',10,'USD',30,'image-banner'),
('mexc','MEXC','exchange',2,8,true,'https://www.mexc.com/acquisition/custom-sign-up?shareCode=mexc-Btccalctool','https://www.mexc.com/acquisition/custom-sign-up?shareCode=mexc-Btccalctool',ARRAY['dca','investment','profit-loss','mining-profitability','time-machine','what-if','lump-sum-vs-dca','savings','average-buy-price','bitcoin-savings','stack-sats','sip','lot-size','arbitrage']::text[],ARRAY['trading','buy-bitcoin','accumulation']::text[],ARRAY[]::text[],'high',40,'USD',60,'image-banner'),
('bybit','Bybit','trading',2,7,true,'https://www.bybit.com/invite?ref=160486','https://www.bybit.com/invite?ref=160486',ARRAY['lot-size','volatility','leverage-liquidation','arbitrage','correlation','cagr','dominance','bitcoin-lot-size','lightning','lump-sum-vs-dca']::text[],ARRAY['trading','professional','active']::text[],ARRAY[]::text[],'high',30,'USD',30,'single-card'),
('tradingview','TradingView','trading',1,9,true,'https://www.tradingview.com/?aff_id=166891&aff_sub=creative&utm_source=bitcoincalculator&utm_medium=referral&utm_campaign=creative_en','https://www.tradingview.com/?aff_id=166891&aff_sub=creative&utm_source=bitcoincalculator&utm_medium=referral&utm_campaign=creative_tr',ARRAY['*']::text[],ARRAY['*']::text[],ARRAY[]::text[],'medium',15,'USD',30,'image-banner'),
('redotpay','RedotPay','card',1,9,true,'https://wap.redotpay.com/en/invite/affiliates-1?utm_id=36rgik&utm_source=union&utm_uid=15980&utm_s=f29a110dc987f17ad366813652572664712174e0','https://wap.redotpay.com/en/invite/affiliates-1?utm_id=36rgik&utm_source=union&utm_uid=15980&utm_s=f29a110dc987f17ad366813652572664712174e0',ARRAY['*']::text[],ARRAY['profit','cashout','spend','high-value']::text[],ARRAY[]::text[],'high',20,'USD',365,'image-banner'),
('axi','Axi','trading',1,9,true,'https://www.axi.com/int/live-account?promocode=4744672','https://www.axi.com/int/live-account?promocode=4744672',ARRAY['lot-size','liquidation','leverage','leverage-liquidation','profit-loss','risk-reward','pip-value','volatility','dca','lump-sum-vs-dca','rainbow-chart','power-law','sip','what-if','bitcoin-lot-size','bitcoin-liquidation','bitcoin-leverage','bitcoin-profit-loss','bitcoin-risk-reward','bitcoin-tasfiye','bitcoin-dca','bitcoin-rainbow-chart','bitcoin-power-law','bitcoin-sip','bitcoin-what-if']::text[],ARRAY['trading','active','leverage','high-risk']::text[],ARRAY[]::text[],'high',400,'USD',90,'image-banner')
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, category=EXCLUDED.category, tier=EXCLUDED.tier, priority=EXCLUDED.priority,
  enabled=true, url_en=EXCLUDED.url_en, url_tr=EXCLUDED.url_tr,
  target_pages=EXCLUDED.target_pages, target_results=EXCLUDED.target_results,
  language_restriction=EXCLUDED.language_restriction, conversion_intent=EXCLUDED.conversion_intent,
  commission_rate=EXCLUDED.commission_rate, commission_currency=EXCLUDED.commission_currency,
  cookie_days=EXCLUDED.cookie_days, default_format=EXCLUDED.default_format, updated_at=now();